import { MORE_GAMES } from './catalog-more.ts'

export type Category =
  | 'party'
  | 'social deduction'
  | 'word'
  | 'drawing'
  | 'strategy'
  | 'card game'
  | 'co-op'
  | 'classic'
  | 'family'
  | 'trivia'

export type Price = 'free' | 'freemium' | 'paid'

export interface GameLink {
  label: string
  url: string
  note?: string
}

export interface GameMeta {
  slug: string
  name: string
  tagline: string
  description: string
  minPlayers: number
  maxPlayers: number
  /** Sweet spot player counts. */
  bestPlayers: number[]
  minMinutes: number
  maxMinutes: number
  /** 1 = pick up instantly, 5 = heavy. */
  complexity: 1 | 2 | 3 | 4 | 5
  categories: Category[]
  tags: string[]
  emoji: string
  gradient: string
  links: GameLink[]
  price: Price
  /** Needs a video/voice call alongside it to work well. */
  needsCall?: boolean
}

export const CATEGORY_INFO: Record<Category, { emoji: string; blurb: string }> = {
  party: { emoji: '🎉', blurb: 'Loud, fast, and great with a big group.' },
  'social deduction': { emoji: '🕵️', blurb: 'Hidden roles, bluffing, and accusing your friends.' },
  word: { emoji: '🔤', blurb: 'Clues, vocab, and clever associations.' },
  drawing: { emoji: '🎨', blurb: 'Doodle, guess, and laugh at the results.' },
  strategy: { emoji: '🧠', blurb: 'Deeper games that reward planning.' },
  'card game': { emoji: '🃏', blurb: 'Hands, tricks, and drafting.' },
  'co-op': { emoji: '🤝', blurb: 'Everyone wins or loses together.' },
  classic: { emoji: '♟️', blurb: 'Timeless games everyone already knows.' },
  family: { emoji: '👨‍👩‍👧', blurb: 'Easy to teach, fun for all ages.' },
  trivia: { emoji: '🧩', blurb: 'Know things. Guess things. Bet on things.' },
}

const BGA = (game: string) => `https://en.boardgamearena.com/gamepanel?game=${game}`

export const CATALOG: GameMeta[] = [
  {
    slug: 'codenames',
    name: 'Codenames',
    tagline: 'One-word clues, 25 words, two rival spymasters.',
    description:
      'Two teams race to contact all their secret agents. Each spymaster gives one-word clues that point to several words on the grid — but one of them is the assassin.',
    minPlayers: 4,
    maxPlayers: 12,
    bestPlayers: [6, 8],
    minMinutes: 15,
    maxMinutes: 30,
    complexity: 1,
    categories: ['party', 'word', 'family'],
    tags: ['teams', 'clues', 'official'],
    emoji: '🕵️',
    gradient: 'from-rose-500 via-red-600 to-sky-600',
    price: 'free',
    needsCall: true,
    links: [
      { label: 'codenames.game', url: 'https://codenames.game', note: 'Official — includes Duet & Pictures' },
      { label: 'Horsepaste', url: 'https://horsepaste.com', note: 'Minimal fan version' },
    ],
  },
  {
    slug: 'one-night-werewolf',
    name: 'One Night Ultimate Werewolf',
    tagline: 'One night, one vote. Find the werewolves before dawn.',
    description: 'Fast, no-elimination Werewolf. Everyone gets a secret role, the night shuffles who knows what, then a single vote decides it all.',
    minPlayers: 3,
    maxPlayers: 10,
    bestPlayers: [5, 6, 7],
    minMinutes: 10,
    maxMinutes: 15,
    complexity: 1,
    categories: ['social deduction', 'party'],
    tags: ['hidden roles', 'bluffing', 'quick'],
    emoji: '🐺',
    gradient: 'from-indigo-700 via-violet-800 to-slate-900',
    price: 'free',
    needsCall: true,
    links: [
      { label: 'netgames.io', url: 'https://netgames.io/games/onu-werewolf/', note: 'Free, no accounts' },
      { label: 'onenightultimate.com', url: 'https://www.onenightultimate.com/', note: 'Official app & narrator' },
    ],
  },
  {
    slug: 'avalon',
    name: 'The Resistance: Avalon',
    tagline: 'Loyal knights vs hidden minions of Mordred.',
    description: 'Good tries to pass three quests while Evil secretly sabotages. Merlin knows who is evil — but if the Assassin guesses Merlin, Evil wins.',
    minPlayers: 5,
    maxPlayers: 10,
    bestPlayers: [7, 8],
    minMinutes: 30,
    maxMinutes: 45,
    complexity: 2,
    categories: ['social deduction'],
    tags: ['hidden roles', 'teams', 'bluffing'],
    emoji: '⚔️',
    gradient: 'from-emerald-700 via-teal-800 to-slate-900',
    price: 'free',
    needsCall: true,
    links: [
      { label: 'avalon.fun', url: 'https://avalon.fun', note: 'Full roles & expansions' },
      { label: 'netgames.io', url: 'https://netgames.io/games/avalon/', note: 'Simple & phone-friendly' },
    ],
  },
  {
    slug: 'secret-hitler',
    name: 'Secret Hitler',
    tagline: 'Liberals vs fascists in 1930s Germany.',
    description: 'Pass policies, elect chancellors, and figure out who is secretly fascist before it is too late. Tense, argumentative, and brilliant.',
    minPlayers: 5,
    maxPlayers: 10,
    bestPlayers: [7, 8],
    minMinutes: 30,
    maxMinutes: 45,
    complexity: 2,
    categories: ['social deduction'],
    tags: ['hidden roles', 'bluffing', 'voting'],
    emoji: '🎩',
    gradient: 'from-orange-600 via-red-700 to-slate-900',
    price: 'free',
    needsCall: true,
    links: [
      { label: 'secrethitler.io', url: 'https://secrethitler.io', note: 'Full online version with chat' },
      { label: 'netgames.io (Secret Sith)', url: 'https://netgames.io/games/secret-sith/', note: 'Reskinned, phone-friendly' },
    ],
  },
  {
    slug: 'spyfall',
    name: 'Spyfall',
    tagline: 'Everyone knows where you are — except the spy.',
    description: 'All players share a secret location except the spy. Ask each other questions to sniff out the spy without giving away where you are.',
    minPlayers: 3,
    maxPlayers: 10,
    bestPlayers: [5, 6],
    minMinutes: 8,
    maxMinutes: 15,
    complexity: 1,
    categories: ['social deduction', 'party'],
    tags: ['bluffing', 'quick', 'questions'],
    emoji: '🔎',
    gradient: 'from-amber-500 via-orange-600 to-rose-700',
    price: 'free',
    needsCall: true,
    links: [
      { label: 'spyfall.adrianocola.com', url: 'https://spyfall.adrianocola.com', note: 'Spyfall 1 & 2 locations' },
      { label: 'netgames.io', url: 'https://netgames.io/games/spyfall/' },
      { label: 'spyfall.app', url: 'https://spyfall.app' },
    ],
  },
  {
    slug: 'coup',
    name: 'Coup',
    tagline: 'Bluff your way to the last player standing.',
    description: 'Two hidden influence cards each. Claim any role you like — tax, assassinate, steal — and dare anyone to call your bluff.',
    minPlayers: 2,
    maxPlayers: 6,
    bestPlayers: [4, 5],
    minMinutes: 10,
    maxMinutes: 15,
    complexity: 1,
    categories: ['card game', 'social deduction', 'party'],
    tags: ['bluffing', 'quick', 'elimination'],
    emoji: '👑',
    gradient: 'from-yellow-600 via-amber-700 to-stone-900',
    price: 'free',
    links: [{ label: 'Treason Coup', url: 'https://coup.thebrown.net', note: 'Play with friends or AI' }],
  },
  {
    slug: 'love-letter',
    name: 'Love Letter',
    tagline: 'Sixteen cards, one princess, pure deduction.',
    description: 'A tiny hand-management game of deduction and risk. Get your letter to the princess by knocking out rivals with just one card in hand.',
    minPlayers: 2,
    maxPlayers: 6,
    bestPlayers: [3, 4],
    minMinutes: 15,
    maxMinutes: 20,
    complexity: 1,
    categories: ['card game', 'family'],
    tags: ['deduction', 'quick', 'micro game'],
    emoji: '💌',
    gradient: 'from-pink-500 via-rose-600 to-red-800',
    price: 'free',
    links: [
      { label: 'netgames.io', url: 'https://netgames.io/games/love-letter/' },
      { label: 'Board Game Arena', url: BGA('loveletter') },
    ],
  },
  {
    slug: 'enigma',
    name: 'Enigma',
    tagline: 'Decrypt your team’s code before the enemy does.',
    description: 'A Decrypto-style team game: give clues for a three-digit code so your team gets it, while the other team tries to intercept.',
    minPlayers: 4,
    maxPlayers: 8,
    bestPlayers: [4, 6],
    minMinutes: 20,
    maxMinutes: 30,
    complexity: 2,
    categories: ['word', 'party'],
    tags: ['teams', 'clues', 'codes'],
    emoji: '🔐',
    gradient: 'from-slate-600 via-slate-800 to-black',
    price: 'free',
    needsCall: true,
    links: [
      { label: 'netgames.io', url: 'https://netgames.io/games/enigma/' },
      { label: 'Decrypto Online', url: 'https://decrypto.online', note: 'Fan version of the original' },
    ],
  },
  {
    slug: 'wavelength',
    name: 'Wavelength',
    tagline: 'Read your friends’ minds on a spectrum.',
    description: 'One player sees a hidden target on a spectrum like “hot ↔ cold” and gives a clue. The team argues about where the dial should go.',
    minPlayers: 2,
    maxPlayers: 12,
    bestPlayers: [6, 8],
    minMinutes: 30,
    maxMinutes: 45,
    complexity: 1,
    categories: ['party', 'family'],
    tags: ['teams', 'discussion', 'official'],
    emoji: '📡',
    gradient: 'from-cyan-500 via-sky-600 to-indigo-800',
    price: 'free',
    needsCall: true,
    links: [
      { label: 'wavelength.zone', url: 'https://www.wavelength.zone', note: 'Official web version' },
      { label: 'Longwave', url: 'https://longwave.web.app', note: 'Free fan version' },
    ],
  },
  {
    slug: 'gartic-phone',
    name: 'Gartic Phone',
    tagline: 'Telestrations: draw, describe, repeat, laugh.',
    description: 'Telephone-game meets drawing. Write a prompt, draw someone else’s, describe someone else’s drawing — and watch the chaos unfold at the end.',
    minPlayers: 4,
    maxPlayers: 30,
    bestPlayers: [6, 8, 10],
    minMinutes: 10,
    maxMinutes: 20,
    complexity: 1,
    categories: ['drawing', 'party'],
    tags: ['telestrations', 'big groups', 'silly'],
    emoji: '📞',
    gradient: 'from-fuchsia-500 via-purple-600 to-indigo-700',
    price: 'free',
    links: [{ label: 'garticphone.com', url: 'https://garticphone.com' }],
  },
  {
    slug: 'skribbl',
    name: 'skribbl.io',
    tagline: 'Pictionary in your browser.',
    description: 'Take turns drawing a word while everyone else races to guess it. Custom word lists make it great for inside jokes.',
    minPlayers: 2,
    maxPlayers: 20,
    bestPlayers: [5, 8],
    minMinutes: 10,
    maxMinutes: 20,
    complexity: 1,
    categories: ['drawing', 'party', 'family'],
    tags: ['pictionary', 'quick', 'custom words'],
    emoji: '✏️',
    gradient: 'from-lime-400 via-green-500 to-emerald-700',
    price: 'free',
    links: [
      { label: 'skribbl.io', url: 'https://skribbl.io' },
      { label: 'Sketchful', url: 'https://sketchful.io', note: 'Similar, more modes' },
      { label: 'Drawbattle', url: 'https://drawbattle.io', note: 'Team-based drawing' },
    ],
  },
  {
    slug: 'fishbowl',
    name: 'Fishbowl',
    tagline: 'Taboo, then Password, then Charades — same words.',
    description: 'Three rounds with the same set of words: describe freely, then one word only, then act it out. Escalating hilarity for teams.',
    minPlayers: 4,
    maxPlayers: 20,
    bestPlayers: [6, 8],
    minMinutes: 30,
    maxMinutes: 45,
    complexity: 1,
    categories: ['party', 'word'],
    tags: ['teams', 'charades', 'big groups'],
    emoji: '🐟',
    gradient: 'from-sky-400 via-blue-600 to-indigo-800',
    price: 'free',
    needsCall: true,
    links: [{ label: 'fishbowl-game.com', url: 'https://fishbowl-game.com' }],
  },
  {
    slug: 'jklm',
    name: 'JKLM.fun (BombParty & more)',
    tagline: 'Type a word containing the syllable before the bomb explodes.',
    description: 'A collection of quick word party games. BombParty is the star: pass the bomb by typing a word containing the given letters — fast.',
    minPlayers: 2,
    maxPlayers: 50,
    bestPlayers: [6, 10],
    minMinutes: 5,
    maxMinutes: 15,
    complexity: 1,
    categories: ['word', 'party'],
    tags: ['fast', 'typing', 'big groups'],
    emoji: '💣',
    gradient: 'from-red-500 via-orange-600 to-yellow-500',
    price: 'free',
    links: [{ label: 'jklm.fun', url: 'https://jklm.fun' }],
  },
  {
    slug: 'scattergories',
    name: 'Scattergories',
    tagline: 'One letter, twelve categories, sixty seconds.',
    description: 'Roll a letter, then name something in each category that starts with it. Unique answers score; matching answers cancel.',
    minPlayers: 2,
    maxPlayers: 12,
    bestPlayers: [4, 6],
    minMinutes: 15,
    maxMinutes: 30,
    complexity: 1,
    categories: ['word', 'party', 'family'],
    tags: ['timer', 'categories', 'classic'],
    emoji: '⏱️',
    gradient: 'from-teal-400 via-cyan-600 to-blue-800',
    price: 'free',
    links: [{ label: 'scattergoriesonline.net', url: 'https://scattergoriesonline.net' }],
  },
  {
    slug: 'cards-against-humanity',
    name: 'Cards Against Humanity',
    tagline: 'A party game for horrible people.',
    description: 'Fill in the blank with the most outrageous white card in your hand. The Card Czar picks a winner. Not for the easily offended.',
    minPlayers: 3,
    maxPlayers: 20,
    bestPlayers: [5, 8],
    minMinutes: 30,
    maxMinutes: 60,
    complexity: 1,
    categories: ['party', 'card game'],
    tags: ['adult', 'humor', 'big groups'],
    emoji: '🃏',
    gradient: 'from-zinc-800 via-neutral-900 to-black',
    price: 'free',
    links: [
      { label: 'Pretend You’re Xyzzy', url: 'https://pretendyoure.xyz/zy/', note: 'Free clone with custom decks' },
      { label: 'cardsagainsthumanity.com', url: 'https://www.cardsagainsthumanity.com/', note: 'Official' },
    ],
  },
  {
    slug: 'jackbox',
    name: 'Jackbox Party Packs',
    tagline: 'Quiplash, Fibbage, Drawful — phones as controllers.',
    description: 'One person owns and streams the game; everyone else joins from their phone at jackbox.tv. The gold standard for remote party nights.',
    minPlayers: 2,
    maxPlayers: 10,
    bestPlayers: [6, 8],
    minMinutes: 15,
    maxMinutes: 30,
    complexity: 1,
    categories: ['party', 'trivia', 'drawing'],
    tags: ['streaming', 'phones', 'audience mode'],
    emoji: '📦',
    gradient: 'from-violet-500 via-fuchsia-600 to-pink-600',
    price: 'paid',
    needsCall: true,
    links: [{ label: 'jackboxgames.com', url: 'https://www.jackboxgames.com/games', note: 'One host needs to own a pack' }],
  },
  {
    slug: 'kahoot',
    name: 'Kahoot!',
    tagline: 'Live quizzes, phones as buzzers.',
    description: 'Make or pick a quiz, host it on a shared screen, and everyone answers from their phone. Great for trivia nights.',
    minPlayers: 2,
    maxPlayers: 50,
    bestPlayers: [6, 12],
    minMinutes: 10,
    maxMinutes: 30,
    complexity: 1,
    categories: ['trivia', 'party'],
    tags: ['quiz', 'big groups', 'custom questions'],
    emoji: '❓',
    gradient: 'from-purple-600 via-indigo-700 to-blue-800',
    price: 'freemium',
    links: [{ label: 'kahoot.it', url: 'https://kahoot.it' }],
  },
  {
    slug: 'geoguessr',
    name: 'GeoGuessr',
    tagline: 'Dropped somewhere on Earth. Where are you?',
    description: 'Explore a Street View location and pin it on the map. Duel friends or play party modes — surprisingly competitive.',
    minPlayers: 1,
    maxPlayers: 10,
    bestPlayers: [2, 4],
    minMinutes: 10,
    maxMinutes: 30,
    complexity: 1,
    categories: ['trivia', 'party'],
    tags: ['geography', 'maps', 'duels'],
    emoji: '🌍',
    gradient: 'from-green-500 via-emerald-700 to-teal-900',
    price: 'freemium',
    links: [{ label: 'geoguessr.com', url: 'https://www.geoguessr.com' }],
  },
  {
    slug: 'mafia',
    name: 'Mafia / Werewolf (classic)',
    tagline: 'The original town-vs-mafia elimination game.',
    description: 'Each night the mafia picks a victim; each day the town votes someone out. Long-form social deduction with a moderator.',
    minPlayers: 6,
    maxPlayers: 20,
    bestPlayers: [8, 12],
    minMinutes: 30,
    maxMinutes: 90,
    complexity: 2,
    categories: ['social deduction', 'party'],
    tags: ['hidden roles', 'elimination', 'big groups'],
    emoji: '🌙',
    gradient: 'from-slate-700 via-slate-900 to-black',
    price: 'free',
    needsCall: true,
    links: [{ label: 'mafia.gg', url: 'https://mafia.gg', note: 'Text-based, no moderator needed' }],
  },
  {
    slug: 'hanabi',
    name: 'Hanabi',
    tagline: 'You see everyone’s hand but your own.',
    description: 'Co-operatively build fireworks in order by giving limited clues. Tense, thoughtful, and endlessly replayable.',
    minPlayers: 2,
    maxPlayers: 5,
    bestPlayers: [3, 4],
    minMinutes: 25,
    maxMinutes: 30,
    complexity: 2,
    categories: ['co-op', 'card game'],
    tags: ['clues', 'memory', 'variants'],
    emoji: '🎆',
    gradient: 'from-indigo-500 via-purple-700 to-slate-900',
    price: 'free',
    links: [
      { label: 'hanab.live', url: 'https://hanab.live', note: 'Serious community, tons of variants' },
      { label: 'Board Game Arena', url: BGA('hanabi') },
    ],
  },
  {
    slug: 'the-crew',
    name: 'The Crew',
    tagline: 'A co-op trick-taking mission to Planet Nine.',
    description: 'Win specific tricks together with almost no communication. Fifty escalating missions make it a campaign you play in short bursts.',
    minPlayers: 2,
    maxPlayers: 5,
    bestPlayers: [4],
    minMinutes: 20,
    maxMinutes: 30,
    complexity: 2,
    categories: ['co-op', 'card game'],
    tags: ['trick-taking', 'missions', 'campaign'],
    emoji: '🚀',
    gradient: 'from-sky-700 via-indigo-800 to-slate-950',
    price: 'free',
    links: [{ label: 'Board Game Arena', url: BGA('thecrew') }],
  },
  {
    slug: 'pandemic',
    name: 'Pandemic',
    tagline: 'Cure four diseases before the world falls.',
    description: 'The classic co-op. Travel the globe, treat outbreaks, and coordinate your unique roles to find every cure in time.',
    minPlayers: 2,
    maxPlayers: 4,
    bestPlayers: [4],
    minMinutes: 45,
    maxMinutes: 60,
    complexity: 2,
    categories: ['co-op', 'strategy'],
    tags: ['roles', 'tense', 'planning'],
    emoji: '🧬',
    gradient: 'from-emerald-600 via-green-800 to-slate-900',
    price: 'freemium',
    links: [{ label: 'Board Game Arena', url: BGA('pandemic') }],
  },
  {
    slug: 'the-mind',
    name: 'The Mind',
    tagline: 'Play cards in order without saying a word.',
    description: 'Everyone has numbered cards. Play them in ascending order across all hands — with zero communication. Weirdly magical.',
    minPlayers: 2,
    maxPlayers: 4,
    bestPlayers: [3, 4],
    minMinutes: 15,
    maxMinutes: 20,
    complexity: 1,
    categories: ['co-op', 'card game', 'party'],
    tags: ['silent', 'quick', 'vibes'],
    emoji: '🧘',
    gradient: 'from-violet-400 via-purple-600 to-indigo-900',
    price: 'free',
    needsCall: true,
    links: [{ label: 'themind.online', url: 'https://themind.online' }],
  },
  {
    slug: 'catan',
    name: 'Catan',
    tagline: 'Settle, trade, build — the modern classic.',
    description: 'Gather resources by dice, trade with rivals, and build roads and cities to ten points. The gateway game for a reason.',
    minPlayers: 3,
    maxPlayers: 4,
    bestPlayers: [4],
    minMinutes: 60,
    maxMinutes: 90,
    complexity: 2,
    categories: ['strategy', 'family', 'classic'],
    tags: ['trading', 'dice', 'gateway'],
    emoji: '🐑',
    gradient: 'from-amber-500 via-orange-700 to-red-900',
    price: 'freemium',
    links: [
      { label: 'Colonist', url: 'https://colonist.io', note: 'Free, fast, no accounts needed' },
      { label: 'Board Game Arena', url: BGA('catan') },
    ],
  },
  {
    slug: 'carcassonne',
    name: 'Carcassonne',
    tagline: 'Lay tiles, place meeples, build medieval France.',
    description: 'Draw a tile, add it to the shared map, and claim cities, roads and fields with your followers. Simple rules, real tension.',
    minPlayers: 2,
    maxPlayers: 5,
    bestPlayers: [2, 3],
    minMinutes: 30,
    maxMinutes: 45,
    complexity: 2,
    categories: ['strategy', 'family', 'classic'],
    tags: ['tile laying', 'gateway'],
    emoji: '🏰',
    gradient: 'from-lime-600 via-green-700 to-emerald-900',
    price: 'freemium',
    links: [{ label: 'Board Game Arena', url: BGA('carcassonne') }],
  },
  {
    slug: 'ticket-to-ride',
    name: 'Ticket to Ride',
    tagline: 'Claim train routes across the continent.',
    description: 'Collect colored cards, claim routes, and complete secret destination tickets. Easy to teach, sneaky to master.',
    minPlayers: 2,
    maxPlayers: 5,
    bestPlayers: [3, 4],
    minMinutes: 30,
    maxMinutes: 60,
    complexity: 2,
    categories: ['strategy', 'family'],
    tags: ['set collection', 'routes', 'gateway'],
    emoji: '🚂',
    gradient: 'from-red-500 via-rose-700 to-slate-900',
    price: 'freemium',
    links: [
      { label: 'Board Game Arena', url: BGA('tickettoride') },
      { label: 'ticket-to-ride.com', url: 'https://www.ticket-to-ride.com', note: 'Official apps' },
    ],
  },
  {
    slug: 'azul',
    name: 'Azul',
    tagline: 'Draft gorgeous tiles for the palace walls.',
    description: 'Take all tiles of one color from a factory display and place them on your board. Beautiful, tactical, and a little mean.',
    minPlayers: 2,
    maxPlayers: 4,
    bestPlayers: [2, 3],
    minMinutes: 30,
    maxMinutes: 45,
    complexity: 2,
    categories: ['strategy', 'family'],
    tags: ['drafting', 'abstract', 'pattern building'],
    emoji: '🟦',
    gradient: 'from-blue-500 via-indigo-600 to-cyan-800',
    price: 'freemium',
    links: [{ label: 'Board Game Arena', url: BGA('azul') }],
  },
  {
    slug: 'splendor',
    name: 'Splendor',
    tagline: 'Gems, engines, and Renaissance merchants.',
    description: 'Collect gem chips, buy development cards that give permanent bonuses, and attract nobles. A pure, elegant engine-builder.',
    minPlayers: 2,
    maxPlayers: 4,
    bestPlayers: [2, 3],
    minMinutes: 30,
    maxMinutes: 30,
    complexity: 2,
    categories: ['strategy', 'card game'],
    tags: ['engine building', 'gateway'],
    emoji: '💎',
    gradient: 'from-emerald-400 via-teal-600 to-slate-900',
    price: 'freemium',
    links: [{ label: 'Board Game Arena', url: BGA('splendor') }],
  },
  {
    slug: 'seven-wonders',
    name: '7 Wonders',
    tagline: 'Draft cards to build an ancient civilization.',
    description: 'Simultaneous card drafting across three ages. Scales to seven players without slowing down — a rare feat.',
    minPlayers: 3,
    maxPlayers: 7,
    bestPlayers: [4, 5, 6],
    minMinutes: 30,
    maxMinutes: 45,
    complexity: 2,
    categories: ['strategy', 'card game'],
    tags: ['drafting', 'civilization', 'scales well'],
    emoji: '🏛️',
    gradient: 'from-yellow-500 via-amber-700 to-stone-900',
    price: 'freemium',
    links: [
      { label: 'Board Game Arena', url: BGA('sevenwonders') },
      { label: '7 Wonders Duel (2p)', url: BGA('sevenwondersduel') },
    ],
  },
  {
    slug: 'wingspan',
    name: 'Wingspan',
    tagline: 'Attract birds to your wildlife preserve.',
    description: 'A relaxing engine-builder with 170 gorgeous bird cards. Each bird adds a power to one of your habitats.',
    minPlayers: 1,
    maxPlayers: 5,
    bestPlayers: [2, 3],
    minMinutes: 45,
    maxMinutes: 75,
    complexity: 3,
    categories: ['strategy'],
    tags: ['engine building', 'cozy', 'solo mode'],
    emoji: '🐦',
    gradient: 'from-sky-400 via-teal-600 to-emerald-900',
    price: 'freemium',
    links: [{ label: 'Board Game Arena', url: BGA('wingspan') }],
  },
  {
    slug: 'terraforming-mars',
    name: 'Terraforming Mars',
    tagline: 'Corporations race to make Mars habitable.',
    description: 'Raise the temperature, oxygen and oceans while building a card engine of hundreds of projects. Heavy, long, and beloved.',
    minPlayers: 1,
    maxPlayers: 5,
    bestPlayers: [3],
    minMinutes: 90,
    maxMinutes: 150,
    complexity: 4,
    categories: ['strategy'],
    tags: ['engine building', 'heavy', 'long'],
    emoji: '🔴',
    gradient: 'from-orange-600 via-red-800 to-slate-950',
    price: 'free',
    links: [
      { label: 'Open-source web version', url: 'https://terraforming-mars.herokuapp.com', note: 'Free, all expansions' },
      { label: 'Board Game Arena', url: BGA('terraformingmars') },
    ],
  },
  {
    slug: 'dominion',
    name: 'Dominion',
    tagline: 'The original deck-builder.',
    description: 'Start with ten weak cards and buy your way to a lean, mean deck. Every game uses a different set of ten kingdom cards.',
    minPlayers: 2,
    maxPlayers: 4,
    bestPlayers: [2, 3],
    minMinutes: 30,
    maxMinutes: 30,
    complexity: 2,
    categories: ['card game', 'strategy'],
    tags: ['deck building', 'classic'],
    emoji: '🏯',
    gradient: 'from-amber-600 via-yellow-800 to-stone-900',
    price: 'freemium',
    links: [{ label: 'dominion.games', url: 'https://dominion.games', note: 'Official online client' }],
  },
  {
    slug: 'sushi-go',
    name: 'Sushi Go!',
    tagline: 'Pick-and-pass sushi drafting.',
    description: 'Draft the tastiest combination of sushi dishes as hands pass around the table. Cute, quick, and easy to teach.',
    minPlayers: 2,
    maxPlayers: 5,
    bestPlayers: [3, 4],
    minMinutes: 15,
    maxMinutes: 20,
    complexity: 1,
    categories: ['card game', 'family'],
    tags: ['drafting', 'quick', 'cute'],
    emoji: '🍣',
    gradient: 'from-pink-400 via-rose-500 to-orange-500',
    price: 'freemium',
    links: [{ label: 'Board Game Arena', url: BGA('sushigo') }],
  },
  {
    slug: 'skull',
    name: 'Skull',
    tagline: 'Flowers or skull? The purest bluffing game.',
    description: 'Stack discs face down, then bet how many flowers you can flip without hitting a skull. Win two challenges to win.',
    minPlayers: 3,
    maxPlayers: 6,
    bestPlayers: [4, 5, 6],
    minMinutes: 15,
    maxMinutes: 30,
    complexity: 1,
    categories: ['party', 'social deduction'],
    tags: ['bluffing', 'quick', 'bidding'],
    emoji: '💀',
    gradient: 'from-fuchsia-700 via-purple-800 to-slate-900',
    price: 'freemium',
    links: [{ label: 'Board Game Arena', url: BGA('skull') }],
  },
  {
    slug: 'saboteur',
    name: 'Saboteur',
    tagline: 'Dwarves dig for gold — some are traitors.',
    description: 'Lay tunnel tiles toward the gold, but hidden saboteurs are quietly leading everyone astray. Light hidden-role fun.',
    minPlayers: 3,
    maxPlayers: 10,
    bestPlayers: [6, 7, 8],
    minMinutes: 30,
    maxMinutes: 30,
    complexity: 1,
    categories: ['social deduction', 'card game', 'family'],
    tags: ['hidden roles', 'tile laying'],
    emoji: '⛏️',
    gradient: 'from-yellow-700 via-amber-900 to-stone-950',
    price: 'freemium',
    links: [{ label: 'Board Game Arena', url: BGA('saboteur') }],
  },
  {
    slug: 'king-of-tokyo',
    name: 'King of Tokyo',
    tagline: 'Giant monsters, Yahtzee dice, city smashing.',
    description: 'Roll dice to attack, heal, gain energy or score. Be the last monster standing or the first to twenty points.',
    minPlayers: 2,
    maxPlayers: 6,
    bestPlayers: [4, 5],
    minMinutes: 30,
    maxMinutes: 30,
    complexity: 1,
    categories: ['family', 'party'],
    tags: ['dice', 'king of the hill', 'chaos'],
    emoji: '🦖',
    gradient: 'from-green-500 via-lime-700 to-slate-900',
    price: 'freemium',
    links: [{ label: 'Board Game Arena', url: BGA('kingoftokyo') }],
  },
  {
    slug: 'kingdomino',
    name: 'Kingdomino',
    tagline: 'Dominoes meets kingdom building.',
    description: 'Pick a domino tile, place it in your 5×5 kingdom, and score by matching terrain and crowns. A perfect 15-minute filler.',
    minPlayers: 2,
    maxPlayers: 4,
    bestPlayers: [4],
    minMinutes: 15,
    maxMinutes: 20,
    complexity: 1,
    categories: ['family', 'strategy'],
    tags: ['tile laying', 'quick', 'gateway'],
    emoji: '🏞️',
    gradient: 'from-green-400 via-yellow-500 to-amber-700',
    price: 'freemium',
    links: [{ label: 'Board Game Arena', url: BGA('kingdomino') }],
  },
  {
    slug: 'patchwork',
    name: 'Patchwork',
    tagline: 'Two players sew the best quilt.',
    description: 'Buy Tetris-like fabric pieces with buttons and time. A tight two-player puzzle that plays in twenty minutes.',
    minPlayers: 2,
    maxPlayers: 2,
    bestPlayers: [2],
    minMinutes: 20,
    maxMinutes: 30,
    complexity: 2,
    categories: ['strategy', 'family'],
    tags: ['two player', 'puzzle', 'polyominoes'],
    emoji: '🧵',
    gradient: 'from-rose-400 via-pink-600 to-purple-800',
    price: 'freemium',
    links: [{ label: 'Board Game Arena', url: BGA('patchwork') }],
  },
  {
    slug: 'jaipur',
    name: 'Jaipur',
    tagline: 'Two rival merchants trade for the Maharaja.',
    description: 'Take goods, sell sets for tokens, and manage your camels. One of the best two-player card games ever made.',
    minPlayers: 2,
    maxPlayers: 2,
    bestPlayers: [2],
    minMinutes: 30,
    maxMinutes: 30,
    complexity: 1,
    categories: ['card game', 'strategy'],
    tags: ['two player', 'set collection'],
    emoji: '🐪',
    gradient: 'from-orange-400 via-amber-600 to-yellow-800',
    price: 'freemium',
    links: [{ label: 'Board Game Arena', url: BGA('jaipur') }],
  },
  {
    slug: 'lost-cities',
    name: 'Lost Cities',
    tagline: 'Fund expeditions — but only ones you can finish.',
    description: 'Play ascending cards to five expeditions. Start one and you are committed, so know when to hold back.',
    minPlayers: 2,
    maxPlayers: 2,
    bestPlayers: [2],
    minMinutes: 20,
    maxMinutes: 30,
    complexity: 1,
    categories: ['card game', 'strategy'],
    tags: ['two player', 'press your luck'],
    emoji: '🗺️',
    gradient: 'from-emerald-500 via-green-700 to-stone-900',
    price: 'freemium',
    links: [{ label: 'Board Game Arena', url: BGA('lostcities') }],
  },
  {
    slug: 'welcome-to',
    name: 'Welcome To…',
    tagline: 'Roll-and-write suburbia for any number of players.',
    description: 'Flip cards, write house numbers on your street, and build pools, parks and fences. Everyone plays simultaneously.',
    minPlayers: 1,
    maxPlayers: 100,
    bestPlayers: [4, 6],
    minMinutes: 25,
    maxMinutes: 30,
    complexity: 2,
    categories: ['family', 'strategy'],
    tags: ['roll and write', 'simultaneous', 'any count'],
    emoji: '🏘️',
    gradient: 'from-teal-300 via-cyan-500 to-blue-700',
    price: 'freemium',
    links: [
      { label: 'Board Game Arena', url: BGA('welcometo') },
      { label: 'Railroad Ink (similar)', url: BGA('railroadink') },
    ],
  },
  {
    slug: 'cant-stop',
    name: 'Can’t Stop',
    tagline: 'Push your luck up the mountain.',
    description: 'Roll four dice, pair them, and climb columns. Stop and bank progress — or roll again and risk losing it all.',
    minPlayers: 2,
    maxPlayers: 4,
    bestPlayers: [3, 4],
    minMinutes: 30,
    maxMinutes: 30,
    complexity: 1,
    categories: ['family', 'classic'],
    tags: ['dice', 'press your luck', 'quick'],
    emoji: '🎲',
    gradient: 'from-red-400 via-orange-500 to-yellow-600',
    price: 'free',
    links: [
      { label: 'Board Game Arena', url: BGA('cantstop') },
      { label: 'Incan Gold (similar)', url: BGA('incangold') },
    ],
  },
  {
    slug: 'no-thanks',
    name: 'No Thanks!',
    tagline: 'Take the card or pay a chip. Fewest points wins.',
    description: 'A tiny auction game about knowing when a bad card is actually a good one. Teaches in a minute, plays in fifteen.',
    minPlayers: 3,
    maxPlayers: 7,
    bestPlayers: [4, 5],
    minMinutes: 15,
    maxMinutes: 20,
    complexity: 1,
    categories: ['card game', 'family', 'party'],
    tags: ['auction', 'quick', 'filler'],
    emoji: '🙅',
    gradient: 'from-red-500 via-rose-600 to-pink-700',
    price: 'free',
    links: [{ label: 'Board Game Arena', url: BGA('nothanks') }],
  },
  {
    slug: 'wizard',
    name: 'Wizard',
    tagline: 'Trick-taking where you bet your exact wins.',
    description: 'Predict exactly how many tricks you will take each round. Hit it for points, miss and pay. Skull King is a pirate-flavored cousin.',
    minPlayers: 3,
    maxPlayers: 6,
    bestPlayers: [4, 5],
    minMinutes: 45,
    maxMinutes: 45,
    complexity: 2,
    categories: ['card game', 'classic'],
    tags: ['trick-taking', 'bidding'],
    emoji: '🧙',
    gradient: 'from-indigo-500 via-blue-700 to-slate-900',
    price: 'free',
    links: [
      { label: 'Wizard on BGA', url: BGA('wizard') },
      { label: 'Skull King on BGA', url: BGA('skullking') },
    ],
  },
  {
    slug: 'concept',
    name: 'Concept',
    tagline: 'Charades with icons instead of gestures.',
    description: 'Place markers on a board of universal icons to get your team to guess a word, film or person. No talking allowed.',
    minPlayers: 4,
    maxPlayers: 12,
    bestPlayers: [6, 8],
    minMinutes: 40,
    maxMinutes: 40,
    complexity: 1,
    categories: ['party', 'word', 'family'],
    tags: ['icons', 'teams', 'guessing'],
    emoji: '💭',
    gradient: 'from-sky-500 via-blue-600 to-violet-700',
    price: 'freemium',
    needsCall: true,
    links: [{ label: 'Board Game Arena', url: BGA('concept') }],
  },
  {
    slug: 'set',
    name: 'SET',
    tagline: 'Spot three cards that match — or all differ.',
    description: 'Real-time pattern recognition. Everyone stares at twelve cards and shouts “SET!” Brutal, addictive, and fair.',
    minPlayers: 1,
    maxPlayers: 20,
    bestPlayers: [2, 4],
    minMinutes: 10,
    maxMinutes: 20,
    complexity: 1,
    categories: ['family', 'classic', 'party'],
    tags: ['real-time', 'pattern', 'quick'],
    emoji: '🔺',
    gradient: 'from-purple-500 via-green-500 to-red-500',
    price: 'free',
    links: [{ label: 'Set with Friends', url: 'https://setwithfriends.com' }],
  },
  {
    slug: 'chess',
    name: 'Chess',
    tagline: 'The game of kings, instantly online.',
    description: 'Play a friend by link, solve puzzles, or watch grandmasters. Lichess is free and open source; Chess.com has the biggest community.',
    minPlayers: 2,
    maxPlayers: 2,
    bestPlayers: [2],
    minMinutes: 5,
    maxMinutes: 60,
    complexity: 3,
    categories: ['classic', 'strategy'],
    tags: ['two player', 'abstract', 'puzzles'],
    emoji: '♟️',
    gradient: 'from-stone-300 via-stone-600 to-stone-900',
    price: 'free',
    links: [
      { label: 'Lichess', url: 'https://lichess.org', note: 'Free & open source' },
      { label: 'Chess.com', url: 'https://www.chess.com' },
    ],
  },
  {
    slug: 'go',
    name: 'Go',
    tagline: 'Surround territory on a 19×19 grid.',
    description: 'Simple rules, staggering depth. Play live or correspondence games against friends or the ladder.',
    minPlayers: 2,
    maxPlayers: 2,
    bestPlayers: [2],
    minMinutes: 20,
    maxMinutes: 90,
    complexity: 4,
    categories: ['classic', 'strategy'],
    tags: ['two player', 'abstract', 'deep'],
    emoji: '⚫',
    gradient: 'from-neutral-200 via-neutral-500 to-black',
    price: 'free',
    links: [{ label: 'Online Go Server', url: 'https://online-go.com' }],
  },
  {
    slug: 'scrabble',
    name: 'Scrabble',
    tagline: 'Triple word score.',
    description: 'The classic crossword game, officially online. Play friends in real time or take turns over a day.',
    minPlayers: 2,
    maxPlayers: 4,
    bestPlayers: [2],
    minMinutes: 30,
    maxMinutes: 60,
    complexity: 2,
    categories: ['word', 'classic', 'family'],
    tags: ['vocabulary', 'tiles', 'official'],
    emoji: '🔠',
    gradient: 'from-red-600 via-rose-800 to-slate-900',
    price: 'freemium',
    links: [{ label: 'playscrabble.com', url: 'https://playscrabble.com', note: 'Official' }],
  },
  {
    slug: 'classic-card-games',
    name: 'Hearts, Spades & Classic Card Games',
    tagline: 'Every card game your grandparents knew.',
    description: 'Hearts, Spades, Euchre, Rummy, Gin, Crazy Eights, Backgammon, Checkers and more — free, instant, and with private tables for friends.',
    minPlayers: 2,
    maxPlayers: 6,
    bestPlayers: [4],
    minMinutes: 10,
    maxMinutes: 45,
    complexity: 1,
    categories: ['classic', 'card game', 'family'],
    tags: ['trick-taking', 'no signup', 'instant'],
    emoji: '♠️',
    gradient: 'from-green-700 via-emerald-900 to-black',
    price: 'free',
    links: [
      { label: 'CardGames.io', url: 'https://cardgames.io', note: 'No signup, private tables' },
      { label: 'CardzMania', url: 'https://www.cardzmania.com' },
      { label: 'PlayOK', url: 'https://www.playok.com', note: 'Huge classic-game lobby' },
      { label: 'Hearts on BGA', url: BGA('hearts') },
    ],
  },
  {
    slug: 'poker',
    name: 'Poker Night',
    tagline: 'Texas Hold’em with friends, no real money.',
    description: 'Spin up a private table with a link and play Hold’em or Omaha with play chips. Perfect over a video call.',
    minPlayers: 2,
    maxPlayers: 10,
    bestPlayers: [6, 8],
    minMinutes: 30,
    maxMinutes: 120,
    complexity: 2,
    categories: ['classic', 'card game'],
    tags: ['bluffing', 'betting', 'private tables'],
    emoji: '🂡',
    gradient: 'from-green-600 via-green-900 to-black',
    price: 'free',
    links: [{ label: 'PokerNow', url: 'https://www.pokernow.com', note: 'Private tables, no signup' }],
  },
  {
    slug: 'uno-and-more',
    name: 'Uno-style & Light Card Games',
    tagline: 'Fluxx, Coloretto, Lucky Numbers, 6 nimmt!…',
    description: 'Easygoing card games for when nobody wants to think too hard. All free to play on Board Game Arena.',
    minPlayers: 2,
    maxPlayers: 6,
    bestPlayers: [4],
    minMinutes: 15,
    maxMinutes: 30,
    complexity: 1,
    categories: ['card game', 'family'],
    tags: ['light', 'filler', 'kids'],
    emoji: '🌈',
    gradient: 'from-yellow-400 via-red-500 to-blue-600',
    price: 'free',
    links: [
      { label: 'Fluxx', url: BGA('fluxx') },
      { label: 'Coloretto', url: BGA('coloretto') },
      { label: 'Lucky Numbers', url: BGA('luckynumbers') },
    ],
  },
  {
    slug: 'heavy-euros',
    name: 'Heavy Euro Games',
    tagline: 'Agricola, Castles of Burgundy, Gaia Project, Ark Nova…',
    description: 'For the table that wants a real brain-burner. Turn-based on Board Game Arena so long games can span days.',
    minPlayers: 1,
    maxPlayers: 5,
    bestPlayers: [3, 4],
    minMinutes: 90,
    maxMinutes: 180,
    complexity: 5,
    categories: ['strategy'],
    tags: ['heavy', 'turn-based', 'long'],
    emoji: '⚙️',
    gradient: 'from-stone-500 via-stone-700 to-slate-950',
    price: 'freemium',
    links: [
      { label: 'Ark Nova', url: BGA('arknova') },
      { label: 'Castles of Burgundy', url: BGA('castlesofburgundy') },
      { label: 'Gaia Project', url: BGA('gaiaproject') },
      { label: 'Agricola', url: BGA('agricola') },
      { label: 'Puerto Rico', url: BGA('puertorico') },
      { label: 'Viticulture', url: BGA('viticulture') },
    ],
  },
  {
    slug: 'playingcards-io',
    name: 'Playingcards.io (any card game)',
    tagline: 'A virtual table for the game that isn’t here.',
    description: 'Build any card or board game with a shared virtual table: decks, tokens, dice, and hidden hands. Great for house rules.',
    minPlayers: 1,
    maxPlayers: 20,
    bestPlayers: [4],
    minMinutes: 10,
    maxMinutes: 120,
    complexity: 1,
    categories: ['classic', 'card game'],
    tags: ['sandbox', 'custom', 'any game'],
    emoji: '🎴',
    gradient: 'from-slate-500 via-slate-700 to-slate-900',
    price: 'free',
    links: [
      { label: 'playingcards.io', url: 'https://playingcards.io' },
      { label: 'Tabletopia', url: 'https://tabletopia.com', note: '3D tables, huge library' },
      { label: 'Tabletop Simulator', url: 'https://www.tabletopsimulator.com', note: 'Paid, Steam' },
    ],
  },
  ...MORE_GAMES,
]

export const CATALOG_BY_SLUG: Record<string, GameMeta> = Object.fromEntries(CATALOG.map((g) => [g.slug, g]))

export const ALL_CATEGORIES = Object.keys(CATEGORY_INFO) as Category[]

export interface Filters {
  query: string
  category: Category | null
  players: number | null
  maxTime: number | null
  maxComplexity: number | null
  freeOnly: boolean
}

export const EMPTY_FILTERS: Filters = { query: '', category: null, players: null, maxTime: null, maxComplexity: null, freeOnly: false }

export function searchCatalog(f: Filters): GameMeta[] {
  const q = f.query.trim().toLowerCase()
  return CATALOG.filter((g) => {
    if (f.category && !g.categories.includes(f.category)) return false
    if (f.players !== null && (f.players < g.minPlayers || f.players > g.maxPlayers)) return false
    if (f.maxTime !== null && g.minMinutes > f.maxTime) return false
    if (f.maxComplexity !== null && g.complexity > f.maxComplexity) return false
    if (f.freeOnly && g.price === 'paid') return false
    if (!q) return true
    const hay = [g.name, g.tagline, g.description, ...g.categories, ...g.tags, ...g.links.map((l) => l.label)].join(' ').toLowerCase()
    return q.split(/\s+/).every((word) => hay.includes(word))
  })
}

export function formatPlayers(g: GameMeta) {
  if (g.maxPlayers >= 20) return `${g.minPlayers}+`
  return g.minPlayers === g.maxPlayers ? `${g.minPlayers}` : `${g.minPlayers}–${g.maxPlayers}`
}

export function formatTime(g: GameMeta) {
  return g.minMinutes === g.maxMinutes ? `${g.minMinutes} min` : `${g.minMinutes}–${g.maxMinutes} min`
}

export const COMPLEXITY_LABEL = ['', 'Light', 'Easy', 'Medium', 'Heavy', 'Brain-burner']
