import type { GameMeta } from './catalog.ts'

const BGA = (game: string) => `https://en.boardgamearena.com/gamepanel?game=${game}`

/** Second batch: real tabletop games with a free (or free-tier) browser version. */
export const MORE_GAMES: GameMeta[] = [
  {
    slug: 'decrypto',
    name: 'Decrypto',
    tagline: 'Encrypt for your team without the other side cracking your code.',
    description: 'Two teams share four secret keywords each. Give three clues that map to a 3-digit code — clear enough for your team, vague enough that the enemy cannot intercept.',
    minPlayers: 3,
    maxPlayers: 8,
    bestPlayers: [4, 6],
    minMinutes: 15,
    maxMinutes: 45,
    complexity: 2,
    categories: ['word', 'party'],
    tags: ['teams', 'clues', 'codes'],
    emoji: '🔐',
    gradient: 'from-lime-500 via-emerald-700 to-slate-900',
    price: 'free',
    needsCall: true,
    links: [{ label: 'decrypto.online', url: 'https://decrypto.online' }],
  },
  {
    slug: 'just-one',
    name: 'Just One',
    tagline: 'Everyone writes one clue. Duplicates get erased.',
    description: 'A fully cooperative word game: the guesser looks away, everyone else writes one clue word, matching clues are removed, and the guesser has one shot.',
    minPlayers: 3,
    maxPlayers: 7,
    bestPlayers: [5, 6, 7],
    minMinutes: 20,
    maxMinutes: 20,
    complexity: 1,
    categories: ['word', 'co-op', 'party', 'family'],
    tags: ['clues', 'cooperative', 'Spiel des Jahres'],
    emoji: '1️⃣',
    gradient: 'from-yellow-400 via-amber-500 to-orange-700',
    price: 'freemium',
    links: [{ label: 'Board Game Arena', url: BGA('justone') }],
  },
  {
    slug: 'werewords',
    name: 'Werewords',
    tagline: 'Twenty Questions, but one of you is a werewolf.',
    description: 'The Mayor knows a secret word and answers yes/no questions in four minutes. The Seer knows it too; the werewolf knows it and is trying to derail you.',
    minPlayers: 4,
    maxPlayers: 10,
    bestPlayers: [6, 7, 8],
    minMinutes: 10,
    maxMinutes: 10,
    complexity: 1,
    categories: ['social deduction', 'word', 'party'],
    tags: ['hidden roles', 'fast', 'official app'],
    emoji: '🐺',
    gradient: 'from-purple-600 via-fuchsia-800 to-slate-900',
    price: 'free',
    needsCall: true,
    links: [{ label: 'werewords.com', url: 'https://werewords.com', note: 'Official — free companion app runs the timer & roles' }],
  },
  {
    slug: 'town-of-salem',
    name: 'Town of Salem',
    tagline: 'Werewolf at scale, with dozens of roles.',
    description: 'A 7–15 player Mafia variant with Town, Mafia, and Neutral roles like Jailor, Serial Killer and Jester. Lynch by day, act by night, lie constantly.',
    minPlayers: 7,
    maxPlayers: 15,
    bestPlayers: [15],
    minMinutes: 20,
    maxMinutes: 40,
    complexity: 2,
    categories: ['social deduction'],
    tags: ['hidden roles', 'big group', 'public lobbies'],
    emoji: '⚰️',
    gradient: 'from-stone-600 via-stone-800 to-black',
    price: 'freemium',
    links: [{ label: 'Town of Salem', url: 'https://www.blankmediagames.com', note: 'Browser + apps, public lobbies' }],
  },
  {
    slug: 'diplomacy',
    name: 'Diplomacy',
    tagline: 'No dice. Just seven powers and broken promises.',
    description: 'Pre-WWI Europe: all orders resolve simultaneously and nothing is random, so the only way to win is to negotiate — and eventually betray — your allies.',
    minPlayers: 2,
    maxPlayers: 7,
    bestPlayers: [7],
    minMinutes: 240,
    maxMinutes: 600,
    complexity: 3,
    categories: ['strategy', 'classic'],
    tags: ['negotiation', 'play by turn', 'betrayal'],
    emoji: '🗺️',
    gradient: 'from-amber-700 via-yellow-900 to-stone-900',
    price: 'free',
    links: [
      { label: 'Backstabbr', url: 'https://www.backstabbr.com', note: 'Modern UI, private games' },
      { label: 'webDiplomacy', url: 'https://webdiplomacy.net', note: 'Classic community site' },
      { label: 'playdiplomacy', url: 'https://www.playdiplomacy.com' },
    ],
  },
  {
    slug: 'risk-warzone',
    name: 'Risk (Warzone)',
    tagline: 'World conquest, one territory at a time.',
    description: 'Warzone is a free Risk-style game with hundreds of maps, real-time or multi-day turns, and clean rules for reinforcing, attacking and cashing cards.',
    minPlayers: 2,
    maxPlayers: 40,
    bestPlayers: [4, 5, 6],
    minMinutes: 30,
    maxMinutes: 180,
    complexity: 2,
    categories: ['strategy', 'classic'],
    tags: ['area control', 'dice', 'maps'],
    emoji: '🌍',
    gradient: 'from-orange-600 via-red-800 to-slate-900',
    price: 'freemium',
    links: [
      { label: 'Warzone', url: 'https://www.warzone.com' },
      { label: 'Dominating 12', url: 'https://dominating12.com', note: 'Closer to the original board' },
    ],
  },
  {
    slug: 'monopoly-richup',
    name: 'Monopoly (Richup)',
    tagline: 'Buy, build, bankrupt your friends.',
    description: 'Richup.io is a free, browser-based take on the classic property trading game with private rooms, trades, auctions and house rules.',
    minPlayers: 2,
    maxPlayers: 8,
    bestPlayers: [4],
    minMinutes: 45,
    maxMinutes: 120,
    complexity: 1,
    categories: ['classic', 'family'],
    tags: ['trading', 'dice', 'private rooms'],
    emoji: '🏠',
    gradient: 'from-green-600 via-emerald-800 to-slate-900',
    price: 'free',
    links: [{ label: 'richup.io', url: 'https://richup.io' }],
  },
  {
    slug: 'yahtzee',
    name: 'Yahtzee',
    tagline: 'Five dice, three rolls, thirteen boxes.',
    description: 'Roll, keep, reroll, then commit the result to a scoring category. The push-your-luck decision of chasing that Yahtzee never gets old.',
    minPlayers: 1,
    maxPlayers: 4,
    bestPlayers: [2],
    minMinutes: 15,
    maxMinutes: 30,
    complexity: 1,
    categories: ['classic', 'family'],
    tags: ['dice', 'quick', 'solo'],
    emoji: '🎲',
    gradient: 'from-red-500 via-red-700 to-slate-900',
    price: 'free',
    links: [{ label: 'cardgames.io', url: 'https://cardgames.io/yahtzee/', note: 'Private multiplayer rooms' }],
  },
  {
    slug: 'backgammon',
    name: 'Backgammon',
    tagline: 'Race your checkers home with dice and nerve.',
    description: 'One of the oldest games in the world: move fifteen checkers around the board, hit blots, and know when to double the stakes.',
    minPlayers: 2,
    maxPlayers: 2,
    bestPlayers: [2],
    minMinutes: 15,
    maxMinutes: 30,
    complexity: 2,
    categories: ['classic', 'strategy'],
    tags: ['two player', 'dice', 'ancient'],
    emoji: '🎯',
    gradient: 'from-amber-600 via-orange-800 to-stone-900',
    price: 'free',
    links: [
      { label: 'cardgames.io', url: 'https://cardgames.io/backgammon/' },
      { label: 'Backgammon Galore', url: 'https://bkgm.com', note: 'Rules & strategy' },
    ],
  },
  {
    slug: 'checkers',
    name: 'Checkers / Draughts',
    tagline: 'Jump, capture, king. Lichess for draughts.',
    description: 'Lidraughts is a free, open-source draughts server (international, Brazilian, Russian, and English checkers) with ratings, puzzles and live play.',
    minPlayers: 2,
    maxPlayers: 2,
    bestPlayers: [2],
    minMinutes: 10,
    maxMinutes: 30,
    complexity: 2,
    categories: ['classic', 'strategy'],
    tags: ['two player', 'abstract', 'open source'],
    emoji: '⚪',
    gradient: 'from-red-700 via-stone-800 to-black',
    price: 'free',
    links: [
      { label: 'lidraughts.org', url: 'https://lidraughts.org' },
      { label: 'cardgames.io', url: 'https://cardgames.io/checkers/', note: 'Casual English checkers' },
    ],
  },
  {
    slug: 'hearts-spades',
    name: 'Hearts & Spades',
    tagline: 'The trick-taking classics, with friends in a private room.',
    description: 'Hearts: avoid points, or shoot the moon. Spades: partners bid tricks and spades always trump. Both run in the browser with no accounts.',
    minPlayers: 4,
    maxPlayers: 4,
    bestPlayers: [4],
    minMinutes: 20,
    maxMinutes: 45,
    complexity: 2,
    categories: ['card game', 'classic'],
    tags: ['trick taking', 'partners', 'no account'],
    emoji: '♠️',
    gradient: 'from-slate-700 via-red-900 to-black',
    price: 'free',
    links: [
      { label: 'Hearts', url: 'https://cardgames.io/hearts/' },
      { label: 'Spades', url: 'https://cardgames.io/spades/' },
    ],
  },
  {
    slug: 'hive',
    name: 'Hive',
    tagline: 'Chess with bugs and no board.',
    description: 'Surround the enemy queen bee with a swarm of tiles that each move differently — ants run, grasshoppers jump, beetles climb. Deep, portable, fast.',
    minPlayers: 2,
    maxPlayers: 2,
    bestPlayers: [2],
    minMinutes: 15,
    maxMinutes: 30,
    complexity: 2,
    categories: ['strategy', 'classic'],
    tags: ['two player', 'abstract', 'tiles'],
    emoji: '🐝',
    gradient: 'from-yellow-500 via-amber-700 to-stone-900',
    price: 'free',
    links: [
      { label: 'HiveGame.com', url: 'https://hivegame.com', note: 'Official, free, real-time' },
      { label: 'Board Game Arena', url: BGA('hive') },
    ],
  },
  {
    slug: 'onitama',
    name: 'Onitama',
    tagline: 'Martial-arts chess where the moves pass to your opponent.',
    description: 'Five move cards, always in rotation: the card you use goes to your rival. Capture the master or reach their temple. Elegant and quick.',
    minPlayers: 2,
    maxPlayers: 2,
    bestPlayers: [2],
    minMinutes: 15,
    maxMinutes: 20,
    complexity: 2,
    categories: ['strategy'],
    tags: ['two player', 'abstract', 'quick'],
    emoji: '🥋',
    gradient: 'from-red-600 via-orange-800 to-stone-900',
    price: 'freemium',
    links: [{ label: 'Board Game Arena', url: BGA('onitama') }],
  },
  {
    slug: 'seven-wonders-duel',
    name: '7 Wonders Duel',
    tagline: 'The best two-player civ game, in 30 minutes.',
    description: 'Draft cards from a pyramid layout to build your city, and win by science, military, or points. Tense from the very first pick.',
    minPlayers: 2,
    maxPlayers: 2,
    bestPlayers: [2],
    minMinutes: 30,
    maxMinutes: 30,
    complexity: 2,
    categories: ['strategy', 'card game'],
    tags: ['two player', 'drafting', 'civilization'],
    emoji: '🏛️',
    gradient: 'from-sky-600 via-blue-800 to-slate-900',
    price: 'freemium',
    links: [{ label: 'Board Game Arena', url: BGA('sevenwondersduel') }],
  },
  {
    slug: 'stone-age',
    name: 'Stone Age',
    tagline: 'Feed your tribe, gather resources, build huts.',
    description: 'The friendly gateway to worker placement: send your people to hunt, farm, and chop wood, then roll dice to see how much they bring back.',
    minPlayers: 2,
    maxPlayers: 4,
    bestPlayers: [3, 4],
    minMinutes: 60,
    maxMinutes: 90,
    complexity: 2,
    categories: ['strategy', 'family'],
    tags: ['worker placement', 'dice', 'gateway'],
    emoji: '🪨',
    gradient: 'from-stone-500 via-amber-800 to-stone-900',
    price: 'freemium',
    links: [{ label: 'Board Game Arena', url: BGA('stoneage') }],
  },
  {
    slug: 'puerto-rico',
    name: 'Puerto Rico',
    tagline: 'Pick a role, everyone follows, you get the bonus.',
    description: 'Plant crops, build production, and ship goods for points. The role-selection mechanic means every choice you make also helps your rivals.',
    minPlayers: 2,
    maxPlayers: 5,
    bestPlayers: [4, 5],
    minMinutes: 90,
    maxMinutes: 150,
    complexity: 3,
    categories: ['strategy'],
    tags: ['role selection', 'economic', 'classic euro'],
    emoji: '🌽',
    gradient: 'from-yellow-600 via-lime-800 to-emerald-950',
    price: 'freemium',
    links: [{ label: 'Board Game Arena', url: BGA('puertorico') }],
  },
  {
    slug: 'tokaido',
    name: 'Tokaido',
    tagline: 'A relaxing walk across Japan — but never fall too far behind.',
    description: 'Travel the East Sea Road collecting panoramas, meals and hot springs. The player furthest back always moves next, so lingering is a strategy.',
    minPlayers: 2,
    maxPlayers: 5,
    bestPlayers: [4, 5],
    minMinutes: 45,
    maxMinutes: 45,
    complexity: 1,
    categories: ['family', 'strategy'],
    tags: ['set collection', 'gentle', 'gorgeous'],
    emoji: '🗾',
    gradient: 'from-pink-400 via-rose-600 to-slate-800',
    price: 'freemium',
    links: [{ label: 'Board Game Arena', url: BGA('tokaido') }],
  },
  {
    slug: 'takenoko',
    name: 'Takenoko',
    tagline: 'Grow bamboo. Keep the panda from eating it.',
    description: 'Lay garden tiles, irrigate them, and move the gardener and panda to complete secret objectives. Light, charming, and sneakily tactical.',
    minPlayers: 2,
    maxPlayers: 4,
    bestPlayers: [3, 4],
    minMinutes: 45,
    maxMinutes: 45,
    complexity: 2,
    categories: ['family', 'strategy'],
    tags: ['tile laying', 'objectives', 'panda'],
    emoji: '🐼',
    gradient: 'from-green-500 via-emerald-700 to-slate-900',
    price: 'freemium',
    links: [{ label: 'Board Game Arena', url: BGA('takenoko') }],
  },
  {
    slug: 'six-nimmt',
    name: '6 nimmt!',
    tagline: 'Everyone plays a card at once. Sixth card takes the row.',
    description: 'Simultaneously play numbers onto four rows; if yours is the sixth card, you eat the row and its bull-heads. Chaos with a lot of players.',
    minPlayers: 2,
    maxPlayers: 10,
    bestPlayers: [5, 6, 7, 8],
    minMinutes: 30,
    maxMinutes: 45,
    complexity: 1,
    categories: ['card game', 'party', 'family'],
    tags: ['simultaneous', 'big group', 'quick'],
    emoji: '🐂',
    gradient: 'from-red-500 via-orange-700 to-stone-900',
    price: 'freemium',
    links: [{ label: 'Board Game Arena', url: BGA('sechsnimmt') }],
  },
  {
    slug: 'race-for-the-galaxy',
    name: 'Race for the Galaxy',
    tagline: 'Build a space empire in 12 cards.',
    description: 'Choose phases secretly, then everybody acts in the phases anyone picked. Cards are money and buildings. Dense, fast, endlessly replayable.',
    minPlayers: 2,
    maxPlayers: 4,
    bestPlayers: [2, 3],
    minMinutes: 30,
    maxMinutes: 60,
    complexity: 3,
    categories: ['card game', 'strategy'],
    tags: ['engine building', 'simultaneous', 'sci-fi'],
    emoji: '🚀',
    gradient: 'from-indigo-600 via-violet-900 to-black',
    price: 'freemium',
    links: [{ label: 'Board Game Arena', url: BGA('raceforthegalaxy') }],
  },
  {
    slug: 'coloretto',
    name: 'Coloretto',
    tagline: 'Flip a card or take a row. Three colors count, the rest hurt.',
    description: 'A tiny, perfect push-your-luck game: add chameleons to rows, or grab a row before it gets worse. Only your three biggest colors score.',
    minPlayers: 2,
    maxPlayers: 5,
    bestPlayers: [3, 4],
    minMinutes: 20,
    maxMinutes: 30,
    complexity: 1,
    categories: ['card game', 'family'],
    tags: ['set collection', 'push your luck', 'filler'],
    emoji: '🦎',
    gradient: 'from-lime-400 via-teal-600 to-slate-900',
    price: 'freemium',
    links: [{ label: 'Board Game Arena', url: BGA('coloretto') }],
  },
  {
    slug: 'tichu',
    name: 'Tichu',
    tagline: 'The partnership climbing game with a cult following.',
    description: 'Two teams, shedding-style play with dragons and phoenixes. Call “Tichu” to bet you will go out first. Fast, deep, and addictive.',
    minPlayers: 4,
    maxPlayers: 4,
    bestPlayers: [4],
    minMinutes: 45,
    maxMinutes: 90,
    complexity: 2,
    categories: ['card game', 'strategy'],
    tags: ['partners', 'climbing', 'betting'],
    emoji: '🐉',
    gradient: 'from-red-600 via-yellow-700 to-stone-900',
    price: 'freemium',
    links: [{ label: 'Board Game Arena', url: BGA('tichu') }],
  },
  {
    slug: 'draftosaurus',
    name: 'Draftosaurus',
    tagline: 'Draft dinos into your park, one meeple at a time.',
    description: 'Grab a dinosaur from your hand, pass the rest, and place it in a pen with its own scoring rule — while a die restricts where everyone can build.',
    minPlayers: 2,
    maxPlayers: 5,
    bestPlayers: [3, 4, 5],
    minMinutes: 15,
    maxMinutes: 15,
    complexity: 1,
    categories: ['family', 'party'],
    tags: ['drafting', 'quick', 'kids'],
    emoji: '🦕',
    gradient: 'from-green-500 via-teal-700 to-slate-900',
    price: 'freemium',
    links: [{ label: 'Board Game Arena', url: BGA('draftosaurus') }],
  },
  {
    slug: 'kingdom-builder',
    name: 'Kingdom Builder',
    tagline: 'One card, three houses, and a map that changes every game.',
    description: 'Place settlements on the terrain your card shows, adjacent to your own if you can. Scoring cards and map boards change each time.',
    minPlayers: 2,
    maxPlayers: 5,
    bestPlayers: [3, 4],
    minMinutes: 45,
    maxMinutes: 45,
    complexity: 2,
    categories: ['strategy', 'family'],
    tags: ['area control', 'Spiel des Jahres', 'variable setup'],
    emoji: '🏘️',
    gradient: 'from-emerald-500 via-green-800 to-slate-900',
    price: 'freemium',
    links: [{ label: 'Board Game Arena', url: BGA('kingdombuilder') }],
  },
  {
    slug: 'quoridor',
    name: 'Quoridor',
    tagline: 'Race to the far side — or wall your opponent in.',
    description: 'Each turn either move your pawn or drop a wall. You can never fully block a path, so it becomes a battle of maze-building.',
    minPlayers: 2,
    maxPlayers: 4,
    bestPlayers: [2],
    minMinutes: 15,
    maxMinutes: 15,
    complexity: 1,
    categories: ['strategy', 'classic', 'family'],
    tags: ['abstract', 'two player', 'quick'],
    emoji: '🧱',
    gradient: 'from-amber-500 via-orange-800 to-stone-900',
    price: 'freemium',
    links: [{ label: 'Board Game Arena', url: BGA('quoridor') }],
  },
  {
    slug: 'sea-salt-paper',
    name: 'Sea Salt & Paper',
    tagline: 'Collect pairs, then stop the round when you dare.',
    description: 'Draw from the deck or discards, play pairs for effects, and end the round early — or call “last chance” and bet you will still be ahead.',
    minPlayers: 2,
    maxPlayers: 4,
    bestPlayers: [2, 3],
    minMinutes: 30,
    maxMinutes: 45,
    complexity: 1,
    categories: ['card game', 'family'],
    tags: ['set collection', 'origami art', 'filler'],
    emoji: '🐚',
    gradient: 'from-cyan-400 via-sky-600 to-slate-900',
    price: 'freemium',
    links: [{ label: 'Board Game Arena', url: BGA('seasaltpaper') }],
  },
  {
    slug: 'hanamikoji',
    name: 'Hanamikoji',
    tagline: 'Win the favor of the geisha in four exquisite moves.',
    description: 'Each round you get exactly four actions — keep one card secret, discard two, offer three, or split four. Tiny box, huge tension.',
    minPlayers: 2,
    maxPlayers: 2,
    bestPlayers: [2],
    minMinutes: 15,
    maxMinutes: 15,
    complexity: 2,
    categories: ['card game', 'strategy'],
    tags: ['two player', 'I split you choose', 'quick'],
    emoji: '🌸',
    gradient: 'from-pink-500 via-rose-700 to-slate-900',
    price: 'freemium',
    links: [{ label: 'Board Game Arena', url: BGA('hanamikoji') }],
  },
  {
    slug: 'for-sale',
    name: 'For Sale',
    tagline: 'Buy houses, flip them for cheques. Ten minutes.',
    description: 'Bid on properties in round one, then sell them for cheques in round two. The best filler auction game ever made.',
    minPlayers: 3,
    maxPlayers: 6,
    bestPlayers: [4, 5],
    minMinutes: 15,
    maxMinutes: 15,
    complexity: 1,
    categories: ['card game', 'party', 'family'],
    tags: ['auction', 'filler', 'quick'],
    emoji: '🏷️',
    gradient: 'from-teal-500 via-cyan-700 to-slate-900',
    price: 'freemium',
    links: [{ label: 'Board Game Arena', url: BGA('forsale') }],
  },
  {
    slug: 'incan-gold',
    name: 'Incan Gold',
    tagline: 'Go deeper for treasure or bail before the trap.',
    description: 'Everyone secretly chooses to continue or leave the temple. Leave and you bank your gems; stay and risk losing them to a second hazard.',
    minPlayers: 3,
    maxPlayers: 8,
    bestPlayers: [5, 6, 7],
    minMinutes: 20,
    maxMinutes: 30,
    complexity: 1,
    categories: ['party', 'family'],
    tags: ['push your luck', 'simultaneous', 'Diamant'],
    emoji: '💎',
    gradient: 'from-yellow-500 via-amber-700 to-stone-900',
    price: 'freemium',
    links: [{ label: 'Board Game Arena', url: BGA('incangold') }],
  },
  {
    slug: 'railroad-ink',
    name: 'Railroad Ink',
    tagline: 'Roll the dice, draw the routes, connect the exits.',
    description: 'A roll-and-write where everybody uses the same dice: sketch roads and rails on your grid to connect as many exits as possible in seven rounds.',
    minPlayers: 1,
    maxPlayers: 6,
    bestPlayers: [2, 3, 4],
    minMinutes: 20,
    maxMinutes: 30,
    complexity: 1,
    categories: ['family', 'strategy'],
    tags: ['roll and write', 'solo', 'no interaction'],
    emoji: '🛤️',
    gradient: 'from-slate-500 via-blue-800 to-slate-950',
    price: 'freemium',
    links: [{ label: 'Board Game Arena', url: BGA('railroadink') }],
  },
  {
    slug: 'castles-of-burgundy',
    name: 'The Castles of Burgundy',
    tagline: 'Two dice, a thousand ways to spend them.',
    description: 'Roll dice to buy and place hex tiles into your estate; every completed region scores more the sooner it is done. A modern classic.',
    minPlayers: 2,
    maxPlayers: 4,
    bestPlayers: [2],
    minMinutes: 60,
    maxMinutes: 90,
    complexity: 3,
    categories: ['strategy'],
    tags: ['dice', 'tile placement', 'Feld'],
    emoji: '🏰',
    gradient: 'from-yellow-700 via-amber-900 to-stone-950',
    price: 'freemium',
    links: [{ label: 'Board Game Arena', url: BGA('castlesofburgundy') }],
  },
  {
    slug: 'agricola',
    name: 'Agricola',
    tagline: 'Farm, feed the family, don’t beg.',
    description: 'Worker placement at its most demanding: plow fields, breed animals, and expand your house — all while the harvest keeps coming.',
    minPlayers: 1,
    maxPlayers: 5,
    bestPlayers: [3, 4],
    minMinutes: 90,
    maxMinutes: 150,
    complexity: 4,
    categories: ['strategy'],
    tags: ['worker placement', 'heavy', 'farming'],
    emoji: '🐑',
    gradient: 'from-lime-700 via-green-900 to-stone-950',
    price: 'freemium',
    links: [{ label: 'Board Game Arena', url: BGA('agricola') }],
  },
  {
    slug: 'ark-nova',
    name: 'Ark Nova',
    tagline: 'Build the best zoo in the world.',
    description: 'Balance appeal and conservation while placing enclosures, playing animal cards and running projects. The hottest heavy game of recent years.',
    minPlayers: 1,
    maxPlayers: 4,
    bestPlayers: [2],
    minMinutes: 90,
    maxMinutes: 150,
    complexity: 4,
    categories: ['strategy'],
    tags: ['card driven', 'heavy', 'zoo'],
    emoji: '🦒',
    gradient: 'from-emerald-600 via-green-900 to-stone-950',
    price: 'freemium',
    links: [{ label: 'Board Game Arena', url: BGA('arknova') }],
  },
  {
    slug: 'gaia-project',
    name: 'Gaia Project',
    tagline: 'Terra Mystica in space, for people who like spreadsheets.',
    description: 'Fourteen asymmetric factions terraform and colonise a hex galaxy. Brutal economy, zero luck, enormous decision space.',
    minPlayers: 1,
    maxPlayers: 4,
    bestPlayers: [3, 4],
    minMinutes: 90,
    maxMinutes: 180,
    complexity: 5,
    categories: ['strategy'],
    tags: ['heavy', 'asymmetric', 'sci-fi'],
    emoji: '🪐',
    gradient: 'from-violet-700 via-indigo-950 to-black',
    price: 'freemium',
    links: [{ label: 'Board Game Arena', url: BGA('gaiaproject') }],
  },
  {
    slug: 'through-the-ages',
    name: 'Through the Ages',
    tagline: 'A civilization game with no map — just brilliant card play.',
    description: 'Guide a civilization from antiquity to the modern age: leaders, wonders, technology, and military built entirely from a card row. Long and superb.',
    minPlayers: 2,
    maxPlayers: 4,
    bestPlayers: [3],
    minMinutes: 180,
    maxMinutes: 240,
    complexity: 5,
    categories: ['strategy'],
    tags: ['civilization', 'heavy', 'card driven'],
    emoji: '📜',
    gradient: 'from-amber-800 via-stone-800 to-black',
    price: 'freemium',
    links: [{ label: 'Board Game Arena', url: BGA('throughtheages') }],
  },
  {
    slug: 'boggle-wordshake',
    name: 'Boggle (Wordshake)',
    tagline: 'Find as many words as you can in a 4×4 grid.',
    description: 'A free browser Boggle: three minutes, one letter grid, connect adjacent letters into words. Compare scores with friends on the same grid.',
    minPlayers: 1,
    maxPlayers: 8,
    bestPlayers: [2, 3, 4],
    minMinutes: 3,
    maxMinutes: 10,
    complexity: 1,
    categories: ['word', 'family', 'classic'],
    tags: ['timed', 'quick', 'solo'],
    emoji: '🔠',
    gradient: 'from-orange-400 via-amber-600 to-stone-900',
    price: 'free',
    links: [{ label: 'Wordshake', url: 'https://wordshake.com' }],
  },
  {
    slug: 'connect-four-battleship',
    name: 'Connect 4, Battleship & Gomoku',
    tagline: 'The kitchen-table classics, in a private link.',
    description: 'papergames.io hosts the childhood favourites with private rooms and no downloads: Connect 4, Battleship, Gomoku, Tic-tac-toe and more.',
    minPlayers: 2,
    maxPlayers: 2,
    bestPlayers: [2],
    minMinutes: 5,
    maxMinutes: 15,
    complexity: 1,
    categories: ['classic', 'family'],
    tags: ['two player', 'quick', 'kids'],
    emoji: '🔴',
    gradient: 'from-yellow-400 via-red-600 to-slate-900',
    price: 'free',
    links: [
      { label: 'Connect 4', url: 'https://papergames.io/en/connect4' },
      { label: 'Battleship', url: 'https://papergames.io/en/battleship' },
      { label: 'Gomoku', url: 'https://papergames.io/en/gomoku' },
    ],
  },
  {
    slug: 'wikitrivia',
    name: 'Timeline (Wiki Trivia)',
    tagline: 'Place historical events in the right order.',
    description: 'A free Timeline-style game built on Wikipedia: drag each card to where it belongs in history. One wrong placement and your streak ends.',
    minPlayers: 1,
    maxPlayers: 8,
    bestPlayers: [1, 2],
    minMinutes: 5,
    maxMinutes: 15,
    complexity: 1,
    categories: ['trivia', 'family'],
    tags: ['history', 'solo', 'streak'],
    emoji: '📅',
    gradient: 'from-stone-500 via-stone-700 to-slate-950',
    price: 'free',
    links: [{ label: 'Wiki Trivia', url: 'https://wikitrivia.tomjwatson.com' }],
  },
]
