import type { GameMeta } from './catalog.ts'

const BGA = (game: string) => `https://en.boardgamearena.com/gamepanel?game=${game}`
const bga = (game: string, note = 'Free to play; premium unlocks table creation for some titles') => ({ label: 'Board Game Arena', url: BGA(game), note })

/** Third batch: more real tabletop games playable free in the browser (mostly Board Game Arena). */
export const BATCH3_GAMES: GameMeta[] = [
  {
    slug: 'bang',
    name: 'BANG!',
    tagline: 'Spaghetti-western shootout with hidden roles.',
    description: 'The Sheriff and deputies hunt outlaws, outlaws hunt the Sheriff, and the renegade wants to be the last one standing — but only the Sheriff is public. Shoot, dodge, and guess who is who.',
    minPlayers: 4,
    maxPlayers: 7,
    bestPlayers: [5, 6, 7],
    minMinutes: 20,
    maxMinutes: 40,
    complexity: 2,
    categories: ['social deduction', 'card game', 'party'],
    tags: ['hidden roles', 'western', 'take that'],
    emoji: '🤠',
    gradient: 'from-amber-600 via-orange-800 to-stone-900',
    price: 'free',
    links: [bga('bang')],
  },
  {
    slug: 'coup-city-state',
    name: 'Coup (Board Game Arena)',
    tagline: 'Bluff about your influence; call others out at your peril.',
    description: 'The official Coup implementation on Board Game Arena. Two hidden cards, five roles, and the constant question: are they really the Duke?',
    minPlayers: 2,
    maxPlayers: 6,
    bestPlayers: [4, 5],
    minMinutes: 10,
    maxMinutes: 15,
    complexity: 1,
    categories: ['social deduction', 'card game'],
    tags: ['bluffing', 'elimination', 'filler'],
    emoji: '🗡️',
    gradient: 'from-red-700 via-rose-900 to-black',
    price: 'free',
    links: [bga('coupcitystate')],
  },
  {
    slug: 'good-cop-bad-cop',
    name: 'Good Cop Bad Cop',
    tagline: 'Investigate, equip, and shoot the right leader.',
    description: 'Every player holds three face-down integrity cards; the majority decide whether you are honest or crooked. Investigate neighbours, grab a gun, and take out the enemy leader before they get yours.',
    minPlayers: 4,
    maxPlayers: 8,
    bestPlayers: [6, 7, 8],
    minMinutes: 15,
    maxMinutes: 30,
    complexity: 2,
    categories: ['social deduction', 'party'],
    tags: ['hidden roles', 'teams', 'guns'],
    emoji: '🚔',
    gradient: 'from-blue-700 via-indigo-900 to-black',
    price: 'free',
    links: [bga('goodcopbadcop')],
  },
  {
    slug: 'secret-moon',
    name: 'Secret Moon',
    tagline: 'Love Letter meets hidden teams.',
    description: 'A tiny hidden-team game from the Love Letter designer: the Princess and her allies against the Minister and his. Play cards to peek at loyalties, protect your side, and win by reaching the right power level.',
    minPlayers: 5,
    maxPlayers: 8,
    bestPlayers: [6, 7, 8],
    minMinutes: 15,
    maxMinutes: 20,
    complexity: 1,
    categories: ['social deduction', 'card game'],
    tags: ['hidden teams', 'filler', 'micro game'],
    emoji: '🌙',
    gradient: 'from-purple-700 via-violet-900 to-black',
    price: 'free',
    links: [bga('secretmoon')],
  },
  {
    slug: 'werewolves-millers-hollow',
    name: "The Werewolves of Miller's Hollow",
    tagline: 'The classic full-length Werewolf, with a moderator built in.',
    description: 'The published Werewolf: villagers vote by day, wolves eat by night, and roles like the Seer, Witch and Hunter keep every game different. The app moderates so nobody has to sit out.',
    minPlayers: 8,
    maxPlayers: 18,
    bestPlayers: [10, 12, 14],
    minMinutes: 30,
    maxMinutes: 60,
    complexity: 1,
    categories: ['social deduction', 'party'],
    tags: ['werewolf', 'hidden roles', 'big group'],
    emoji: '🐺',
    gradient: 'from-slate-700 via-slate-900 to-black',
    price: 'free',
    needsCall: true,
    links: [bga('werewolves')],
  },
  {
    slug: 'mascarade',
    name: 'Mascarade',
    tagline: 'Nobody is sure which card they hold — including you.',
    description: 'Cards get swapped face down constantly, so you must claim a role you think you have. Anyone can challenge; get it wrong and you pay. Wild bluffing chaos for big tables.',
    minPlayers: 2,
    maxPlayers: 13,
    bestPlayers: [6, 7, 8],
    minMinutes: 20,
    maxMinutes: 30,
    complexity: 2,
    categories: ['social deduction', 'party', 'card game'],
    tags: ['bluffing', 'memory', 'big group'],
    emoji: '🎭',
    gradient: 'from-fuchsia-600 via-purple-800 to-slate-900',
    price: 'free',
    links: [bga('mascarade')],
  },
  {
    slug: 'inside-job',
    name: 'Inside Job',
    tagline: 'Trick-taking with a traitor.',
    description: 'A cooperative trick-taking heist where one player is secretly working against the team. Complete missions together while trying to spot who is sabotaging tricks.',
    minPlayers: 4,
    maxPlayers: 5,
    bestPlayers: [5],
    minMinutes: 20,
    maxMinutes: 30,
    complexity: 2,
    categories: ['social deduction', 'card game', 'co-op'],
    tags: ['trick-taking', 'traitor', 'heist'],
    emoji: '💼',
    gradient: 'from-zinc-600 via-zinc-800 to-black',
    price: 'free',
    links: [bga('insidejob')],
  },
  {
    slug: 'dark-agent',
    name: 'Dark Agent',
    tagline: 'A game of spies where one of you is the mole.',
    description: 'Agents cooperate on missions while a hidden double agent quietly feeds the enemy. Short, tense and perfect for a group that has burned out on Avalon.',
    minPlayers: 3,
    maxPlayers: 6,
    bestPlayers: [5, 6],
    minMinutes: 20,
    maxMinutes: 30,
    complexity: 2,
    categories: ['social deduction', 'card game'],
    tags: ['spies', 'traitor', 'hidden roles'],
    emoji: '🕶️',
    gradient: 'from-gray-700 via-gray-900 to-black',
    price: 'free',
    links: [bga('darkagent')],
  },
  {
    slug: 'oriflamme',
    name: 'Oriflamme',
    tagline: 'Face-down cards, medieval intrigue, big bluffs.',
    description: 'Each round everyone places a card face down into a shared line, then the line resolves left to right. Assassinate, spy, and bluff about what you actually played.',
    minPlayers: 3,
    maxPlayers: 5,
    bestPlayers: [4, 5],
    minMinutes: 15,
    maxMinutes: 30,
    complexity: 2,
    categories: ['card game', 'strategy'],
    tags: ['bluffing', 'medieval', 'As d’Or'],
    emoji: '🏰',
    gradient: 'from-red-800 via-amber-900 to-black',
    price: 'free',
    links: [bga('oriflamme')],
  },
  {
    slug: 'lucky-numbers',
    name: 'Lucky Numbers',
    tagline: 'Fill a 4×4 grid in ascending order. Deceptively tense.',
    description: 'Draw a tile, place it so every row and column climbs from low to high. A pure filler with just enough spite when you take the tile someone else needed.',
    minPlayers: 1,
    maxPlayers: 4,
    bestPlayers: [3, 4],
    minMinutes: 10,
    maxMinutes: 20,
    complexity: 1,
    categories: ['family', 'classic'],
    tags: ['tiles', 'filler', 'luck'],
    emoji: '🍀',
    gradient: 'from-green-500 via-emerald-700 to-slate-900',
    price: 'free',
    links: [bga('luckynumbers')],
  },
  {
    slug: 'thats-life',
    name: "That's Life!",
    tagline: 'Race your pawns across a track of good and bad fortunes.',
    description: 'Roll, move, and collect the tile you leave behind — most tiles are bad, a few are great, and guardian angels flip everything. Silly, fast and mean.',
    minPlayers: 2,
    maxPlayers: 6,
    bestPlayers: [4, 5],
    minMinutes: 20,
    maxMinutes: 30,
    complexity: 1,
    categories: ['family', 'party'],
    tags: ['dice', 'racing', 'luck'],
    emoji: '🎯',
    gradient: 'from-yellow-400 via-orange-600 to-red-900',
    price: 'free',
    links: [bga('thatslife')],
  },
  {
    slug: 'cubirds',
    name: 'CuBirds',
    tagline: 'Adorable bird set collection in ten minutes.',
    description: 'Play birds onto rows to capture matching flocks, build sets, and race to seven species. Chunky, cute and a lovely first card game for families.',
    minPlayers: 2,
    maxPlayers: 5,
    bestPlayers: [3, 4],
    minMinutes: 10,
    maxMinutes: 20,
    complexity: 1,
    categories: ['card game', 'family'],
    tags: ['set collection', 'birds', 'filler'],
    emoji: '🐦',
    gradient: 'from-sky-400 via-cyan-600 to-blue-900',
    price: 'free',
    links: [bga('cubirds')],
  },
  {
    slug: 'next-station-london',
    name: 'Next Station: London',
    tagline: 'Draw your own Tube map.',
    description: 'A flip-and-write where everyone extends four Underground lines across the same map, scoring for districts, river crossings and tourist spots. Quiet, satisfying and quick.',
    minPlayers: 1,
    maxPlayers: 4,
    bestPlayers: [2, 3, 4],
    minMinutes: 25,
    maxMinutes: 30,
    complexity: 1,
    categories: ['family', 'strategy'],
    tags: ['flip-and-write', 'maps', 'Spiel des Jahres nominee'],
    emoji: '🚇',
    gradient: 'from-red-600 via-blue-800 to-slate-900',
    price: 'free',
    links: [bga('nextstation')],
  },
  {
    slug: 'faraway',
    name: 'Faraway',
    tagline: 'Score your cards in reverse. Brain-bending in the best way.',
    description: 'Play eight cards over eight rounds, but score them last-to-first, so each card can only count things played before it. A tiny, brilliant puzzle.',
    minPlayers: 2,
    maxPlayers: 6,
    bestPlayers: [3, 4],
    minMinutes: 15,
    maxMinutes: 25,
    complexity: 2,
    categories: ['card game', 'strategy'],
    tags: ['tableau', 'puzzle', 'filler'],
    emoji: '🗺️',
    gradient: 'from-teal-500 via-cyan-800 to-slate-900',
    price: 'free',
    links: [bga('faraway')],
  },
  {
    slug: 'harmonies',
    name: 'Harmonies',
    tagline: 'Stack colourful tokens into landscapes for animals.',
    description: 'Build mountains, rivers, forests and fields from coloured tokens, then match the patterns animal cards want. Gorgeous, gentle and moreish.',
    minPlayers: 1,
    maxPlayers: 4,
    bestPlayers: [2, 3],
    minMinutes: 30,
    maxMinutes: 45,
    complexity: 2,
    categories: ['strategy', 'family'],
    tags: ['pattern building', 'nature', 'solo mode'],
    emoji: '🦊',
    gradient: 'from-emerald-500 via-teal-700 to-slate-900',
    price: 'free',
    links: [bga('harmonies')],
  },
  {
    slug: 'akropolis',
    name: 'Akropolis',
    tagline: 'Stack a Greek city in 3D.',
    description: 'Draft tiles and stack them upward — higher districts score more, but only if placed to their liking. Fast, tactile city building; Spiel des Jahres winner.',
    minPlayers: 2,
    maxPlayers: 4,
    bestPlayers: [2, 3],
    minMinutes: 20,
    maxMinutes: 30,
    complexity: 2,
    categories: ['strategy', 'family'],
    tags: ['tile laying', 'city building', 'Spiel des Jahres'],
    emoji: '🏛️',
    gradient: 'from-stone-300 via-sky-600 to-slate-900',
    price: 'free',
    links: [bga('akropolis')],
  },
  {
    slug: 'go-nuts-for-donuts',
    name: 'Go Nuts for Donuts',
    tagline: 'Sushi Go with blind bidding — and donuts.',
    description: 'Everyone secretly picks a donut; if two people want the same one, nobody gets it. Silly set collection that rewards reading your friends.',
    minPlayers: 2,
    maxPlayers: 6,
    bestPlayers: [4, 5],
    minMinutes: 20,
    maxMinutes: 20,
    complexity: 1,
    categories: ['card game', 'family', 'party'],
    tags: ['set collection', 'blind bidding', 'food'],
    emoji: '🍩',
    gradient: 'from-pink-400 via-rose-600 to-fuchsia-900',
    price: 'free',
    links: [bga('gonutsfordonuts')],
  },
  {
    slug: 'red7',
    name: 'Red7',
    tagline: 'Change the rules or be out.',
    description: 'Seven colours, seven rules. At the end of your turn you must be winning under the current rule — play a card to your palette, change the rule, or both. Sharp and tiny.',
    minPlayers: 2,
    maxPlayers: 4,
    bestPlayers: [3, 4],
    minMinutes: 5,
    maxMinutes: 15,
    complexity: 2,
    categories: ['card game'],
    tags: ['rule changing', 'filler', 'quick'],
    emoji: '🔴',
    gradient: 'from-red-500 via-orange-600 to-yellow-700',
    price: 'free',
    links: [bga('redsevengame')],
  },
  {
    slug: 'bandido',
    name: 'Bandido',
    tagline: 'Stop the prisoner escaping — together.',
    description: 'A cooperative tile game: seal off every tunnel before the deck runs out. Ten minutes, one shared brain, endless "no, not there!"',
    minPlayers: 1,
    maxPlayers: 4,
    bestPlayers: [2, 3],
    minMinutes: 10,
    maxMinutes: 15,
    complexity: 1,
    categories: ['co-op', 'family'],
    tags: ['tile laying', 'cooperative', 'filler'],
    emoji: '⛓️',
    gradient: 'from-orange-500 via-amber-800 to-slate-900',
    price: 'free',
    links: [bga('bandido')],
  },
  {
    slug: 'sky-team',
    name: 'Sky Team',
    tagline: 'Land a plane with a co-pilot you cannot talk to.',
    description: 'Pilot and co-pilot secretly roll dice and place them in silence to level the wings, drop the gear and brake in time. A brilliant two-player co-op; Spiel des Jahres 2024.',
    minPlayers: 2,
    maxPlayers: 2,
    bestPlayers: [2],
    minMinutes: 15,
    maxMinutes: 20,
    complexity: 2,
    categories: ['co-op', 'strategy'],
    tags: ['dice', 'two player', 'Spiel des Jahres'],
    emoji: '✈️',
    gradient: 'from-sky-500 via-blue-800 to-slate-950',
    price: 'free',
    links: [bga('skyteam')],
  },
  {
    slug: 'forbidden-island',
    name: 'Forbidden Island',
    tagline: 'Grab the treasures before the island sinks.',
    description: 'From the Pandemic designer: a lighter co-op where tiles flood and vanish while you shuttle treasures to the helicopter. Perfect family gateway co-op.',
    minPlayers: 2,
    maxPlayers: 4,
    bestPlayers: [3, 4],
    minMinutes: 30,
    maxMinutes: 30,
    complexity: 2,
    categories: ['co-op', 'family'],
    tags: ['cooperative', 'adventure', 'gateway'],
    emoji: '🏝️',
    gradient: 'from-cyan-500 via-teal-700 to-slate-900',
    price: 'free',
    links: [bga('forbiddenisland')],
  },
  {
    slug: 'captain-flip',
    name: 'Captain Flip',
    tagline: 'Flip a tile — keep it or take your chances.',
    description: 'Draw a pirate tile, look at one side, and either keep it or flip it and live with whatever is on the back. A push-your-luck tableau builder in 20 minutes.',
    minPlayers: 2,
    maxPlayers: 5,
    bestPlayers: [3, 4],
    minMinutes: 20,
    maxMinutes: 20,
    complexity: 1,
    categories: ['family', 'party'],
    tags: ['push your luck', 'pirates', 'Spiel des Jahres nominee'],
    emoji: '🏴‍☠️',
    gradient: 'from-amber-500 via-red-800 to-slate-900',
    price: 'free',
    links: [bga('captainflip')],
  },
  {
    slug: 'my-city',
    name: 'My City',
    tagline: 'Tetris-style city building on your own board.',
    description: 'Everyone places the same polyomino building as it is called, planning around rivers and rocks. Quick, tactile and great for mixed ages.',
    minPlayers: 2,
    maxPlayers: 4,
    bestPlayers: [3, 4],
    minMinutes: 30,
    maxMinutes: 30,
    complexity: 1,
    categories: ['family', 'strategy'],
    tags: ['polyominoes', 'Knizia', 'city building'],
    emoji: '🏘️',
    gradient: 'from-lime-500 via-green-700 to-slate-900',
    price: 'free',
    links: [bga('mycity')],
  },
  {
    slug: 'earth',
    name: 'Earth',
    tagline: 'Grow an ecosystem in a big, breezy engine builder.',
    description: 'Plant cards into a 4×4 tableau where every action also triggers everyone else. Wingspan-adjacent, very little downtime, and hundreds of unique plants.',
    minPlayers: 1,
    maxPlayers: 5,
    bestPlayers: [2, 3, 4],
    minMinutes: 45,
    maxMinutes: 90,
    complexity: 3,
    categories: ['strategy'],
    tags: ['engine building', 'nature', 'tableau'],
    emoji: '🌍',
    gradient: 'from-green-600 via-emerald-800 to-slate-950',
    price: 'free',
    links: [bga('earth')],
  },
  {
    slug: 'tzolkin',
    name: "Tzolk'in: The Mayan Calendar",
    tagline: 'Worker placement on turning gears.',
    description: 'Place workers on interlocking gears that rotate every round, so your action gets better the longer you wait. Famous, crunchy and wonderfully mechanical.',
    minPlayers: 2,
    maxPlayers: 4,
    bestPlayers: [3, 4],
    minMinutes: 90,
    maxMinutes: 120,
    complexity: 4,
    categories: ['strategy'],
    tags: ['worker placement', 'gears', 'heavy'],
    emoji: '⚙️',
    gradient: 'from-yellow-600 via-amber-900 to-slate-950',
    price: 'free',
    links: [bga('tzolkin')],
  },
  {
    slug: 'terra-mystica',
    name: 'Terra Mystica',
    tagline: 'Terraform the land for your fantasy faction.',
    description: 'Fourteen asymmetric factions compete to transform terrain and spread across a shared map. Zero luck, deep planning, and one of the highest-rated euros ever.',
    minPlayers: 2,
    maxPlayers: 5,
    bestPlayers: [3, 4],
    minMinutes: 90,
    maxMinutes: 150,
    complexity: 4,
    categories: ['strategy'],
    tags: ['asymmetric', 'area control', 'heavy'],
    emoji: '🏔️',
    gradient: 'from-amber-700 via-stone-800 to-black',
    price: 'free',
    links: [bga('terramystica')],
  },
  {
    slug: 'great-western-trail',
    name: 'Great Western Trail',
    tagline: 'Drive cattle to Kansas City in a deckbuilding road trip.',
    description: 'Loop your cowboy along the trail, improving your herd, hiring staff and building stations. Every lap is a fresh puzzle; a modern classic.',
    minPlayers: 2,
    maxPlayers: 4,
    bestPlayers: [3, 4],
    minMinutes: 75,
    maxMinutes: 150,
    complexity: 4,
    categories: ['strategy'],
    tags: ['deckbuilding', 'western', 'heavy'],
    emoji: '🐄',
    gradient: 'from-orange-700 via-amber-900 to-stone-950',
    price: 'free',
    links: [bga('greatwesterntrail')],
  },
  {
    slug: 'beyond-the-sun',
    name: 'Beyond the Sun',
    tagline: 'Research a shared tech tree into the far future.',
    description: 'A space civ game where all players advance one communal technology tree, unlocking new actions and colonising systems. Streamlined for how deep it feels.',
    minPlayers: 2,
    maxPlayers: 4,
    bestPlayers: [3, 4],
    minMinutes: 60,
    maxMinutes: 120,
    complexity: 3,
    categories: ['strategy'],
    tags: ['tech tree', 'space', 'civilization'],
    emoji: '☀️',
    gradient: 'from-orange-500 via-purple-900 to-black',
    price: 'free',
    links: [bga('beyondthesun')],
  },
  {
    slug: 'innovation',
    name: 'Innovation',
    tagline: 'Chaotic civilisation building from Chudyk.',
    description: 'Splay stacks of cards across ten ages, from Writing to the Internet, triggering wild dogma effects that everyone else may share. Swingy, clever and fast.',
    minPlayers: 2,
    maxPlayers: 4,
    bestPlayers: [2],
    minMinutes: 30,
    maxMinutes: 60,
    complexity: 3,
    categories: ['card game', 'strategy'],
    tags: ['civilization', 'chaos', 'two player'],
    emoji: '💡',
    gradient: 'from-yellow-500 via-red-700 to-slate-950',
    price: 'free',
    links: [bga('innovation')],
  },
  {
    slug: 'its-a-wonderful-world',
    name: "It's a Wonderful World",
    tagline: 'Draft, recycle, and build an empire in four rounds.',
    description: 'Draft cards each round, then decide which to build and which to recycle for resources. Tight, quick engine building with a gorgeous dieselpunk look.',
    minPlayers: 1,
    maxPlayers: 5,
    bestPlayers: [3, 4],
    minMinutes: 30,
    maxMinutes: 45,
    complexity: 2,
    categories: ['card game', 'strategy'],
    tags: ['drafting', 'engine building', 'quick'],
    emoji: '🏭',
    gradient: 'from-red-600 via-slate-800 to-black',
    price: 'free',
    links: [bga('itsawonderfulworld')],
  },
  {
    slug: 'nidavellir',
    name: 'Nidavellir',
    tagline: 'Bid coins for dwarves in three taverns.',
    description: 'Secretly bid one of your coins in each tavern, recruit dwarves in bid order, and upgrade your coins to outbid next round. Elegant blind bidding with a Norse flavour.',
    minPlayers: 2,
    maxPlayers: 5,
    bestPlayers: [3, 4],
    minMinutes: 45,
    maxMinutes: 60,
    complexity: 2,
    categories: ['strategy', 'card game'],
    tags: ['bidding', 'set collection', 'dwarves'],
    emoji: '⚒️',
    gradient: 'from-amber-500 via-stone-700 to-slate-950',
    price: 'free',
    links: [bga('nidavellir')],
  },
  {
    slug: 'el-grande',
    name: 'El Grande',
    tagline: 'The grandfather of area control.',
    description: 'Bid power cards to move caballeros into Spanish regions and score majorities. Thirty years old and still the benchmark for area majority games.',
    minPlayers: 2,
    maxPlayers: 5,
    bestPlayers: [5],
    minMinutes: 60,
    maxMinutes: 120,
    complexity: 3,
    categories: ['strategy', 'classic'],
    tags: ['area control', 'Spiel des Jahres', 'classic euro'],
    emoji: '👑',
    gradient: 'from-yellow-500 via-red-800 to-slate-950',
    price: 'free',
    links: [bga('elgrande')],
  },
  {
    slug: 'gizmos',
    name: 'Gizmos',
    tagline: 'Build a chain-reaction contraption.',
    description: 'Pick marbles from a dispenser and build gizmos that trigger each other in satisfying cascades. Light engine building with real "look what my machine does" moments.',
    minPlayers: 2,
    maxPlayers: 4,
    bestPlayers: [2, 3],
    minMinutes: 40,
    maxMinutes: 50,
    complexity: 2,
    categories: ['strategy', 'family'],
    tags: ['engine building', 'chain reactions', 'gateway'],
    emoji: '🔧',
    gradient: 'from-blue-500 via-indigo-800 to-slate-950',
    price: 'free',
    links: [bga('gizmos')],
  },
  {
    slug: 'turing-machine',
    name: 'Turing Machine',
    tagline: 'Deduce the secret code with punch cards.',
    description: 'A competitive deduction puzzle: propose a three-digit code, query the verifiers, and be the first to crack the secret. Feels like Mastermind for grown-ups.',
    minPlayers: 1,
    maxPlayers: 4,
    bestPlayers: [1, 2, 3],
    minMinutes: 20,
    maxMinutes: 20,
    complexity: 2,
    categories: ['strategy', 'trivia'],
    tags: ['deduction', 'logic', 'solo mode'],
    emoji: '🧮',
    gradient: 'from-cyan-500 via-slate-700 to-black',
    price: 'free',
    links: [bga('turingmachine')],
  },
  {
    slug: 'mr-jack',
    name: 'Mr. Jack',
    tagline: 'One hides as Jack the Ripper, one hunts.',
    description: 'A two-player deduction chase through Whitechapel: the detective narrows down which character is Jack while Jack tries to slip out of the district. Tight and tense.',
    minPlayers: 2,
    maxPlayers: 2,
    bestPlayers: [2],
    minMinutes: 20,
    maxMinutes: 30,
    complexity: 2,
    categories: ['strategy'],
    tags: ['deduction', 'two player', 'asymmetric'],
    emoji: '🎩',
    gradient: 'from-slate-600 via-slate-900 to-black',
    price: 'free',
    links: [bga('mrjack')],
  },
  {
    slug: 'downforce',
    name: 'Downforce',
    tagline: 'Bet on the race, then drive every car.',
    description: 'Auction cars, play movement cards that move several cars at once, and bet on the winner mid-race. A Wolfgang Kramer racing classic that always ends in shouting.',
    minPlayers: 2,
    maxPlayers: 6,
    bestPlayers: [4, 5, 6],
    minMinutes: 20,
    maxMinutes: 40,
    complexity: 2,
    categories: ['family', 'party'],
    tags: ['racing', 'betting', 'auction'],
    emoji: '🏎️',
    gradient: 'from-red-500 via-yellow-600 to-slate-900',
    price: 'free',
    links: [bga('downforce')],
  },
  {
    slug: 'seven-wonders-architects',
    name: '7 Wonders: Architects',
    tagline: 'The family-weight 7 Wonders.',
    description: 'Take a card from one of three piles and build your wonder stage by stage. Everything that made 7 Wonders great in half the rules; Kennerspiel winner.',
    minPlayers: 2,
    maxPlayers: 7,
    bestPlayers: [4, 5],
    minMinutes: 25,
    maxMinutes: 25,
    complexity: 1,
    categories: ['family', 'card game'],
    tags: ['drafting', 'gateway', 'big table'],
    emoji: '🏗️',
    gradient: 'from-amber-400 via-orange-700 to-slate-900',
    price: 'free',
    links: [bga('sevenwondersarchitects')],
  },
  {
    slug: 'roll-for-the-galaxy',
    name: 'Roll for the Galaxy',
    tagline: 'Race for the Galaxy, with a cup of dice.',
    description: 'Roll your worker dice, secretly assign them to phases, and build a space empire. Simultaneous turns keep it moving fast.',
    minPlayers: 2,
    maxPlayers: 5,
    bestPlayers: [3, 4],
    minMinutes: 45,
    maxMinutes: 60,
    complexity: 3,
    categories: ['strategy'],
    tags: ['dice', 'space', 'simultaneous'],
    emoji: '🎲',
    gradient: 'from-indigo-500 via-purple-900 to-black',
    price: 'free',
    links: [bga('rollforthegalaxy')],
  },
  {
    slug: 'alhambra',
    name: 'Alhambra',
    tagline: 'Buy buildings with exact change to grow your palace.',
    description: 'Pay for tiles in one of four currencies — exact change earns another turn — and grow the biggest palace complex. Spiel des Jahres 2003.',
    minPlayers: 2,
    maxPlayers: 6,
    bestPlayers: [3, 4],
    minMinutes: 45,
    maxMinutes: 60,
    complexity: 2,
    categories: ['family', 'strategy', 'classic'],
    tags: ['tile laying', 'Spiel des Jahres', 'gateway'],
    emoji: '🕌',
    gradient: 'from-orange-500 via-red-800 to-slate-950',
    price: 'free',
    links: [bga('alhambra')],
  },
  {
    slug: 'parks',
    name: 'Parks',
    tagline: 'Hike America\'s national parks — gorgeously.',
    description: 'Walk two hikers along a trail collecting sunshine, water and wildlife, then spend them to visit parks. Relaxing, beautiful and easy to teach.',
    minPlayers: 1,
    maxPlayers: 5,
    bestPlayers: [2, 3],
    minMinutes: 30,
    maxMinutes: 60,
    complexity: 2,
    categories: ['family', 'strategy'],
    tags: ['nature', 'set collection', 'relaxing'],
    emoji: '🏕️',
    gradient: 'from-green-500 via-orange-700 to-slate-950',
    price: 'free',
    links: [bga('parks')],
  },
  {
    slug: 'exploding-kittens',
    name: 'Exploding Kittens',
    tagline: 'Do not draw the kitten.',
    description: 'Russian roulette with cards: draw an exploding kitten without a defuse and you are out. Skips, attacks and see-the-future cards make it a mean little party game.',
    minPlayers: 2,
    maxPlayers: 5,
    bestPlayers: [4, 5],
    minMinutes: 15,
    maxMinutes: 15,
    complexity: 1,
    categories: ['party', 'card game'],
    tags: ['take that', 'elimination', 'silly'],
    emoji: '🐱',
    gradient: 'from-orange-500 via-red-700 to-black',
    price: 'free',
    links: [bga('explodingkittens')],
  },
  {
    slug: 'fluxx',
    name: 'Fluxx',
    tagline: 'The card game where the rules keep changing.',
    description: 'Start with "draw one, play one" and watch the rules, goals and hand limits mutate every turn. Pure chaos — great for people who like their games unhinged.',
    minPlayers: 2,
    maxPlayers: 6,
    bestPlayers: [3, 4],
    minMinutes: 10,
    maxMinutes: 40,
    complexity: 1,
    categories: ['party', 'card game'],
    tags: ['rule changing', 'chaos', 'silly'],
    emoji: '🌀',
    gradient: 'from-fuchsia-500 via-violet-700 to-slate-950',
    price: 'free',
    links: [bga('fluxx')],
  },
  {
    slug: 'french-tarot',
    name: 'French Tarot',
    tagline: 'The rich, bidding trick-taker France plays at every kitchen table.',
    description: 'A 78-card deck with trumps and the Excuse, one taker against the rest, and bids that decide how much you risk. Deeper than Hearts, quicker than Bridge.',
    minPlayers: 3,
    maxPlayers: 5,
    bestPlayers: [4],
    minMinutes: 20,
    maxMinutes: 45,
    complexity: 3,
    categories: ['classic', 'card game'],
    tags: ['trick-taking', 'bidding', 'traditional'],
    emoji: '🃏',
    gradient: 'from-red-700 via-slate-800 to-black',
    price: 'free',
    links: [bga('frenchtarot')],
  },
  {
    slug: 'skat',
    name: 'Skat',
    tagline: 'Germany\'s national card game.',
    description: 'Three players, 32 cards, and a fiendishly rich bidding system. If you liked Wizard or Hearts and want a lifetime hobby, this is it.',
    minPlayers: 3,
    maxPlayers: 3,
    bestPlayers: [3],
    minMinutes: 20,
    maxMinutes: 40,
    complexity: 3,
    categories: ['classic', 'card game'],
    tags: ['trick-taking', 'bidding', 'traditional'],
    emoji: '♣️',
    gradient: 'from-green-800 via-slate-900 to-black',
    price: 'free',
    links: [bga('skat')],
  },
  {
    slug: 'oh-hell',
    name: 'Oh Hell!',
    tagline: 'Bid exactly how many tricks you will take. Exactly.',
    description: 'The pub trick-taker: hand size changes each round, everyone bids, and you score only if you hit your bid on the nose. Easy to learn, endlessly replayable.',
    minPlayers: 3,
    maxPlayers: 7,
    bestPlayers: [4, 5],
    minMinutes: 30,
    maxMinutes: 45,
    complexity: 1,
    categories: ['classic', 'card game'],
    tags: ['trick-taking', 'bidding', 'traditional'],
    emoji: '😈',
    gradient: 'from-rose-700 via-red-900 to-black',
    price: 'free',
    links: [bga('ohhell')],
  },
  {
    slug: 'rummy',
    name: 'Rummy',
    tagline: 'Sets and runs, the classic way.',
    description: 'Draw, meld sets and sequences, discard, and go out first. The card game half the world grew up on, playable in a browser with friends.',
    minPlayers: 2,
    maxPlayers: 6,
    bestPlayers: [3, 4],
    minMinutes: 15,
    maxMinutes: 30,
    complexity: 1,
    categories: ['classic', 'card game', 'family'],
    tags: ['melding', 'traditional'],
    emoji: '🂡',
    gradient: 'from-emerald-700 via-slate-800 to-black',
    price: 'free',
    links: [bga('rummy')],
  },
  {
    slug: 'dragon-castle',
    name: 'Dragon Castle',
    tagline: 'Mahjong solitaire turned into a competitive board game.',
    description: 'Take matching tiles from a shared mahjong-style castle and rebuild them into your own realm, scoring sets and shrines. Beautiful and unexpectedly tactical.',
    minPlayers: 2,
    maxPlayers: 4,
    bestPlayers: [2, 3],
    minMinutes: 30,
    maxMinutes: 45,
    complexity: 2,
    categories: ['strategy', 'family', 'classic'],
    tags: ['tile laying', 'mahjong', 'pattern building'],
    emoji: '🐉',
    gradient: 'from-red-600 via-amber-800 to-slate-950',
    price: 'free',
    links: [bga('dragoncastle')],
  },
  {
    slug: 'draw-battle',
    name: 'Draw Battle',
    tagline: 'Team Pictionary in the browser.',
    description: 'Split into teams, one person draws while teammates guess against the clock. A free Pictionary-style party game with private rooms.',
    minPlayers: 4,
    maxPlayers: 16,
    bestPlayers: [6, 8, 10],
    minMinutes: 10,
    maxMinutes: 20,
    complexity: 1,
    categories: ['drawing', 'party'],
    tags: ['teams', 'pictionary', 'big group'],
    emoji: '🖌️',
    gradient: 'from-pink-500 via-purple-700 to-slate-950',
    price: 'free',
    needsCall: true,
    links: [{ label: 'drawbattle.io', url: 'https://drawbattle.io' }],
  },
]
